// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_msg_id.proto

#include "cs_msg_id.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace com {
namespace moon {
namespace demo {
namespace cs {
}  // namespace cs
}  // namespace demo
}  // namespace moon
}  // namespace com
namespace protobuf_cs_5fmsg_5fid_2eproto {
void InitDefaults() {
}

const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "cs_msg_id.proto", schemas, file_default_instances, TableStruct::offsets,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017cs_msg_id.proto\022\020com.moon.demo.cs*\271\002\n\005"
      "MsgID\022\020\n\014PLACE_HOLDER\020\000\022\026\n\021MSG_ID_DEMO_1"
      "_REQ\020\350\007\022\026\n\021MSG_ID_DEMO_1_RSP\020\351\007\022\026\n\021MSG_I"
      "D_DEMO_2_REQ\020\352\007\022\026\n\021MSG_ID_DEMO_2_RSP\020\353\007\022"
      "\026\n\021MSG_ID_DEMO_3_REQ\020\354\007\022\026\n\021MSG_ID_DEMO_3"
      "_RSP\020\355\007\022\026\n\021MSG_ID_DEMO_4_REQ\020\356\007\022\026\n\021MSG_I"
      "D_DEMO_4_RSP\020\357\007\022\026\n\021MSG_ID_DEMO_5_REQ\020\360\007\022"
      "\026\n\021MSG_ID_DEMO_5_RSP\020\361\007\022\026\n\021MSG_ID_DEMO_6"
      "_REQ\020\362\007\022\026\n\021MSG_ID_DEMO_6_RSP\020\363\007b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 359);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "cs_msg_id.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_cs_5fmsg_5fid_2eproto
namespace com {
namespace moon {
namespace demo {
namespace cs {
const ::google::protobuf::EnumDescriptor* MsgID_descriptor() {
  protobuf_cs_5fmsg_5fid_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_cs_5fmsg_5fid_2eproto::file_level_enum_descriptors[0];
}
bool MsgID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
    case 1010:
    case 1011:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace cs
}  // namespace demo
}  // namespace moon
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
