// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cs_msg_id.proto

#include "cs_msg_id.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace com {
namespace moon {
namespace demo {
namespace cs {
}  // namespace cs
}  // namespace demo
}  // namespace moon
}  // namespace com
void InitDefaults_cs_5fmsg_5fid_2eproto() {
}

constexpr ::google::protobuf::Metadata* file_level_metadata_cs_5fmsg_5fid_2eproto = nullptr;
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_cs_5fmsg_5fid_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_cs_5fmsg_5fid_2eproto = nullptr;
const ::google::protobuf::uint32 TableStruct_cs_5fmsg_5fid_2eproto::offsets[1] = {};
static constexpr ::google::protobuf::internal::MigrationSchema* schemas = nullptr;
static constexpr ::google::protobuf::Message* const* file_default_instances = nullptr;

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_cs_5fmsg_5fid_2eproto = {
  {}, AddDescriptors_cs_5fmsg_5fid_2eproto, "cs_msg_id.proto", schemas,
  file_default_instances, TableStruct_cs_5fmsg_5fid_2eproto::offsets,
  file_level_metadata_cs_5fmsg_5fid_2eproto, 0, file_level_enum_descriptors_cs_5fmsg_5fid_2eproto, file_level_service_descriptors_cs_5fmsg_5fid_2eproto,
};

const char descriptor_table_protodef_cs_5fmsg_5fid_2eproto[] =
  "\n\017cs_msg_id.proto\022\020com.moon.demo.cs*\213\002\n\005"
  "MsgID\022\020\n\014PLACE_HOLDER\020\000\022\025\n\020MSG_ID_DEMO1_"
  "REQ\020\350\007\022\025\n\020MSG_ID_DEMO1_RSP\020\351\007\022\025\n\020MSG_ID_"
  "DEMO1_NFY\020\352\007\022\025\n\020MSG_ID_DEMO3_NFY\020\353\007\022\027\n\022M"
  "SG_ID_DEMO100_REQ\020\354\007\022\027\n\022MSG_ID_DEMO100_R"
  "SP\020\355\007\022\027\n\022MSG_ID_DEMO200_REQ\020\356\007\022\027\n\022MSG_ID"
  "_DEMO200_RSP\020\357\007\022\027\n\022MSG_ID_DEMO300_REQ\020\360\007"
  "\022\027\n\022MSG_ID_DEMO300_RSP\020\361\007b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_cs_5fmsg_5fid_2eproto = {
  false, InitDefaults_cs_5fmsg_5fid_2eproto, 
  descriptor_table_protodef_cs_5fmsg_5fid_2eproto,
  "cs_msg_id.proto", &assign_descriptors_table_cs_5fmsg_5fid_2eproto, 313,
};

void AddDescriptors_cs_5fmsg_5fid_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_cs_5fmsg_5fid_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cs_5fmsg_5fid_2eproto = []() { AddDescriptors_cs_5fmsg_5fid_2eproto(); return true; }();
namespace com {
namespace moon {
namespace demo {
namespace cs {
const ::google::protobuf::EnumDescriptor* MsgID_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_cs_5fmsg_5fid_2eproto);
  return file_level_enum_descriptors_cs_5fmsg_5fid_2eproto[0];
}
bool MsgID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1000:
    case 1001:
    case 1002:
    case 1003:
    case 1004:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 1009:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace cs
}  // namespace demo
}  // namespace moon
}  // namespace com
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
