// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_msg.proto

#ifndef PROTOBUF_INCLUDED_ss_5fmsg_2eproto
#define PROTOBUF_INCLUDED_ss_5fmsg_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ss_5fmsg_2eproto 

namespace protobuf_ss_5fmsg_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[5];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ss_5fmsg_2eproto
namespace com {
namespace moon {
namespace demo {
namespace proto {
namespace ss {
class Demo1Nfy;
class Demo1NfyDefaultTypeInternal;
extern Demo1NfyDefaultTypeInternal _Demo1Nfy_default_instance_;
class Demo1Req;
class Demo1ReqDefaultTypeInternal;
extern Demo1ReqDefaultTypeInternal _Demo1Req_default_instance_;
class Demo1Rsp;
class Demo1RspDefaultTypeInternal;
extern Demo1RspDefaultTypeInternal _Demo1Rsp_default_instance_;
class GlobalReq;
class GlobalReqDefaultTypeInternal;
extern GlobalReqDefaultTypeInternal _GlobalReq_default_instance_;
class GlobalRsp;
class GlobalRspDefaultTypeInternal;
extern GlobalRspDefaultTypeInternal _GlobalRsp_default_instance_;
}  // namespace ss
}  // namespace proto
}  // namespace demo
}  // namespace moon
}  // namespace com
namespace google {
namespace protobuf {
template<> ::com::moon::demo::proto::ss::Demo1Nfy* Arena::CreateMaybeMessage<::com::moon::demo::proto::ss::Demo1Nfy>(Arena*);
template<> ::com::moon::demo::proto::ss::Demo1Req* Arena::CreateMaybeMessage<::com::moon::demo::proto::ss::Demo1Req>(Arena*);
template<> ::com::moon::demo::proto::ss::Demo1Rsp* Arena::CreateMaybeMessage<::com::moon::demo::proto::ss::Demo1Rsp>(Arena*);
template<> ::com::moon::demo::proto::ss::GlobalReq* Arena::CreateMaybeMessage<::com::moon::demo::proto::ss::GlobalReq>(Arena*);
template<> ::com::moon::demo::proto::ss::GlobalRsp* Arena::CreateMaybeMessage<::com::moon::demo::proto::ss::GlobalRsp>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace com {
namespace moon {
namespace demo {
namespace proto {
namespace ss {

// ===================================================================

class GlobalReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.moon.demo.proto.ss.GlobalReq) */ {
 public:
  GlobalReq();
  virtual ~GlobalReq();

  GlobalReq(const GlobalReq& from);

  inline GlobalReq& operator=(const GlobalReq& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GlobalReq(GlobalReq&& from) noexcept
    : GlobalReq() {
    *this = ::std::move(from);
  }

  inline GlobalReq& operator=(GlobalReq&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GlobalReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlobalReq* internal_default_instance() {
    return reinterpret_cast<const GlobalReq*>(
               &_GlobalReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GlobalReq* other);
  friend void swap(GlobalReq& a, GlobalReq& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GlobalReq* New() const final {
    return CreateMaybeMessage<GlobalReq>(NULL);
  }

  GlobalReq* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GlobalReq>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GlobalReq& from);
  void MergeFrom(const GlobalReq& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlobalReq* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // int32 b = 2;
  void clear_b();
  static const int kBFieldNumber = 2;
  ::google::protobuf::int32 b() const;
  void set_b(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.GlobalReq)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 a_;
  ::google::protobuf::int32 b_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ss_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GlobalRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.moon.demo.proto.ss.GlobalRsp) */ {
 public:
  GlobalRsp();
  virtual ~GlobalRsp();

  GlobalRsp(const GlobalRsp& from);

  inline GlobalRsp& operator=(const GlobalRsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GlobalRsp(GlobalRsp&& from) noexcept
    : GlobalRsp() {
    *this = ::std::move(from);
  }

  inline GlobalRsp& operator=(GlobalRsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GlobalRsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GlobalRsp* internal_default_instance() {
    return reinterpret_cast<const GlobalRsp*>(
               &_GlobalRsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GlobalRsp* other);
  friend void swap(GlobalRsp& a, GlobalRsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GlobalRsp* New() const final {
    return CreateMaybeMessage<GlobalRsp>(NULL);
  }

  GlobalRsp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GlobalRsp>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GlobalRsp& from);
  void MergeFrom(const GlobalRsp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GlobalRsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .com.moon.demo.proto.ErrCtx err_ctx = 1;
  bool has_err_ctx() const;
  void clear_err_ctx();
  static const int kErrCtxFieldNumber = 1;
  private:
  const ::com::moon::demo::proto::ErrCtx& _internal_err_ctx() const;
  public:
  const ::com::moon::demo::proto::ErrCtx& err_ctx() const;
  ::com::moon::demo::proto::ErrCtx* release_err_ctx();
  ::com::moon::demo::proto::ErrCtx* mutable_err_ctx();
  void set_allocated_err_ctx(::com::moon::demo::proto::ErrCtx* err_ctx);

  // @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.GlobalRsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::com::moon::demo::proto::ErrCtx* err_ctx_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ss_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Demo1Req : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.moon.demo.proto.ss.Demo1Req) */ {
 public:
  Demo1Req();
  virtual ~Demo1Req();

  Demo1Req(const Demo1Req& from);

  inline Demo1Req& operator=(const Demo1Req& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Demo1Req(Demo1Req&& from) noexcept
    : Demo1Req() {
    *this = ::std::move(from);
  }

  inline Demo1Req& operator=(Demo1Req&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Demo1Req& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Demo1Req* internal_default_instance() {
    return reinterpret_cast<const Demo1Req*>(
               &_Demo1Req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Demo1Req* other);
  friend void swap(Demo1Req& a, Demo1Req& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Demo1Req* New() const final {
    return CreateMaybeMessage<Demo1Req>(NULL);
  }

  Demo1Req* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Demo1Req>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Demo1Req& from);
  void MergeFrom(const Demo1Req& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Demo1Req* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // bool udp = 2;
  void clear_udp();
  static const int kUdpFieldNumber = 2;
  bool udp() const;
  void set_udp(bool value);

  // @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Req)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 a_;
  bool udp_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ss_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Demo1Rsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.moon.demo.proto.ss.Demo1Rsp) */ {
 public:
  Demo1Rsp();
  virtual ~Demo1Rsp();

  Demo1Rsp(const Demo1Rsp& from);

  inline Demo1Rsp& operator=(const Demo1Rsp& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Demo1Rsp(Demo1Rsp&& from) noexcept
    : Demo1Rsp() {
    *this = ::std::move(from);
  }

  inline Demo1Rsp& operator=(Demo1Rsp&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Demo1Rsp& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Demo1Rsp* internal_default_instance() {
    return reinterpret_cast<const Demo1Rsp*>(
               &_Demo1Rsp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Demo1Rsp* other);
  friend void swap(Demo1Rsp& a, Demo1Rsp& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Demo1Rsp* New() const final {
    return CreateMaybeMessage<Demo1Rsp>(NULL);
  }

  Demo1Rsp* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Demo1Rsp>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Demo1Rsp& from);
  void MergeFrom(const Demo1Rsp& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Demo1Rsp* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .com.moon.demo.proto.ErrCtx err_ctx = 1;
  bool has_err_ctx() const;
  void clear_err_ctx();
  static const int kErrCtxFieldNumber = 1;
  private:
  const ::com::moon::demo::proto::ErrCtx& _internal_err_ctx() const;
  public:
  const ::com::moon::demo::proto::ErrCtx& err_ctx() const;
  ::com::moon::demo::proto::ErrCtx* release_err_ctx();
  ::com::moon::demo::proto::ErrCtx* mutable_err_ctx();
  void set_allocated_err_ctx(::com::moon::demo::proto::ErrCtx* err_ctx);

  // @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Rsp)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::com::moon::demo::proto::ErrCtx* err_ctx_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ss_5fmsg_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Demo1Nfy : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:com.moon.demo.proto.ss.Demo1Nfy) */ {
 public:
  Demo1Nfy();
  virtual ~Demo1Nfy();

  Demo1Nfy(const Demo1Nfy& from);

  inline Demo1Nfy& operator=(const Demo1Nfy& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Demo1Nfy(Demo1Nfy&& from) noexcept
    : Demo1Nfy() {
    *this = ::std::move(from);
  }

  inline Demo1Nfy& operator=(Demo1Nfy&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Demo1Nfy& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Demo1Nfy* internal_default_instance() {
    return reinterpret_cast<const Demo1Nfy*>(
               &_Demo1Nfy_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Demo1Nfy* other);
  friend void swap(Demo1Nfy& a, Demo1Nfy& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Demo1Nfy* New() const final {
    return CreateMaybeMessage<Demo1Nfy>(NULL);
  }

  Demo1Nfy* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Demo1Nfy>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Demo1Nfy& from);
  void MergeFrom(const Demo1Nfy& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Demo1Nfy* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 a = 1;
  void clear_a();
  static const int kAFieldNumber = 1;
  ::google::protobuf::int32 a() const;
  void set_a(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Nfy)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 a_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ss_5fmsg_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GlobalReq

// int32 a = 1;
inline void GlobalReq::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 GlobalReq::a() const {
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.GlobalReq.a)
  return a_;
}
inline void GlobalReq::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:com.moon.demo.proto.ss.GlobalReq.a)
}

// int32 b = 2;
inline void GlobalReq::clear_b() {
  b_ = 0;
}
inline ::google::protobuf::int32 GlobalReq::b() const {
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.GlobalReq.b)
  return b_;
}
inline void GlobalReq::set_b(::google::protobuf::int32 value) {
  
  b_ = value;
  // @@protoc_insertion_point(field_set:com.moon.demo.proto.ss.GlobalReq.b)
}

// -------------------------------------------------------------------

// GlobalRsp

// .com.moon.demo.proto.ErrCtx err_ctx = 1;
inline bool GlobalRsp::has_err_ctx() const {
  return this != internal_default_instance() && err_ctx_ != NULL;
}
inline const ::com::moon::demo::proto::ErrCtx& GlobalRsp::_internal_err_ctx() const {
  return *err_ctx_;
}
inline const ::com::moon::demo::proto::ErrCtx& GlobalRsp::err_ctx() const {
  const ::com::moon::demo::proto::ErrCtx* p = err_ctx_;
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.GlobalRsp.err_ctx)
  return p != NULL ? *p : *reinterpret_cast<const ::com::moon::demo::proto::ErrCtx*>(
      &::com::moon::demo::proto::_ErrCtx_default_instance_);
}
inline ::com::moon::demo::proto::ErrCtx* GlobalRsp::release_err_ctx() {
  // @@protoc_insertion_point(field_release:com.moon.demo.proto.ss.GlobalRsp.err_ctx)
  
  ::com::moon::demo::proto::ErrCtx* temp = err_ctx_;
  err_ctx_ = NULL;
  return temp;
}
inline ::com::moon::demo::proto::ErrCtx* GlobalRsp::mutable_err_ctx() {
  
  if (err_ctx_ == NULL) {
    auto* p = CreateMaybeMessage<::com::moon::demo::proto::ErrCtx>(GetArenaNoVirtual());
    err_ctx_ = p;
  }
  // @@protoc_insertion_point(field_mutable:com.moon.demo.proto.ss.GlobalRsp.err_ctx)
  return err_ctx_;
}
inline void GlobalRsp::set_allocated_err_ctx(::com::moon::demo::proto::ErrCtx* err_ctx) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(err_ctx_);
  }
  if (err_ctx) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      err_ctx = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, err_ctx, submessage_arena);
    }
    
  } else {
    
  }
  err_ctx_ = err_ctx;
  // @@protoc_insertion_point(field_set_allocated:com.moon.demo.proto.ss.GlobalRsp.err_ctx)
}

// -------------------------------------------------------------------

// Demo1Req

// int32 a = 1;
inline void Demo1Req::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 Demo1Req::a() const {
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.Demo1Req.a)
  return a_;
}
inline void Demo1Req::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:com.moon.demo.proto.ss.Demo1Req.a)
}

// bool udp = 2;
inline void Demo1Req::clear_udp() {
  udp_ = false;
}
inline bool Demo1Req::udp() const {
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.Demo1Req.udp)
  return udp_;
}
inline void Demo1Req::set_udp(bool value) {
  
  udp_ = value;
  // @@protoc_insertion_point(field_set:com.moon.demo.proto.ss.Demo1Req.udp)
}

// -------------------------------------------------------------------

// Demo1Rsp

// .com.moon.demo.proto.ErrCtx err_ctx = 1;
inline bool Demo1Rsp::has_err_ctx() const {
  return this != internal_default_instance() && err_ctx_ != NULL;
}
inline const ::com::moon::demo::proto::ErrCtx& Demo1Rsp::_internal_err_ctx() const {
  return *err_ctx_;
}
inline const ::com::moon::demo::proto::ErrCtx& Demo1Rsp::err_ctx() const {
  const ::com::moon::demo::proto::ErrCtx* p = err_ctx_;
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.Demo1Rsp.err_ctx)
  return p != NULL ? *p : *reinterpret_cast<const ::com::moon::demo::proto::ErrCtx*>(
      &::com::moon::demo::proto::_ErrCtx_default_instance_);
}
inline ::com::moon::demo::proto::ErrCtx* Demo1Rsp::release_err_ctx() {
  // @@protoc_insertion_point(field_release:com.moon.demo.proto.ss.Demo1Rsp.err_ctx)
  
  ::com::moon::demo::proto::ErrCtx* temp = err_ctx_;
  err_ctx_ = NULL;
  return temp;
}
inline ::com::moon::demo::proto::ErrCtx* Demo1Rsp::mutable_err_ctx() {
  
  if (err_ctx_ == NULL) {
    auto* p = CreateMaybeMessage<::com::moon::demo::proto::ErrCtx>(GetArenaNoVirtual());
    err_ctx_ = p;
  }
  // @@protoc_insertion_point(field_mutable:com.moon.demo.proto.ss.Demo1Rsp.err_ctx)
  return err_ctx_;
}
inline void Demo1Rsp::set_allocated_err_ctx(::com::moon::demo::proto::ErrCtx* err_ctx) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(err_ctx_);
  }
  if (err_ctx) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      err_ctx = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, err_ctx, submessage_arena);
    }
    
  } else {
    
  }
  err_ctx_ = err_ctx;
  // @@protoc_insertion_point(field_set_allocated:com.moon.demo.proto.ss.Demo1Rsp.err_ctx)
}

// -------------------------------------------------------------------

// Demo1Nfy

// int32 a = 1;
inline void Demo1Nfy::clear_a() {
  a_ = 0;
}
inline ::google::protobuf::int32 Demo1Nfy::a() const {
  // @@protoc_insertion_point(field_get:com.moon.demo.proto.ss.Demo1Nfy.a)
  return a_;
}
inline void Demo1Nfy::set_a(::google::protobuf::int32 value) {
  
  a_ = value;
  // @@protoc_insertion_point(field_set:com.moon.demo.proto.ss.Demo1Nfy.a)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ss
}  // namespace proto
}  // namespace demo
}  // namespace moon
}  // namespace com

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ss_5fmsg_2eproto
