# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_msg.proto',
  package='com.moon.demo.proto.cs',
  syntax='proto2',
  serialized_pb=_b('\n\x0c\x63s_msg.proto\x12\x16\x63om.moon.demo.proto.cs\x1a\x0c\x63ommon.proto\"!\n\x07\x45\x63hoReq\x12\t\n\x01\x61\x18\x01 \x02(\x05\x12\x0b\n\x03udp\x18\x02 \x01(\x08\"7\n\x07\x45\x63hoRsp\x12,\n\x07\x65rr_ctx\x18\x01 \x02(\x0b\x32\x1b.com.moon.demo.proto.ErrCtx')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_ECHOREQ = _descriptor.Descriptor(
  name='EchoReq',
  full_name='com.moon.demo.proto.cs.EchoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='com.moon.demo.proto.cs.EchoReq.a', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='udp', full_name='com.moon.demo.proto.cs.EchoReq.udp', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=87,
)


_ECHORSP = _descriptor.Descriptor(
  name='EchoRsp',
  full_name='com.moon.demo.proto.cs.EchoRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_ctx', full_name='com.moon.demo.proto.cs.EchoRsp.err_ctx', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=144,
)

_ECHORSP.fields_by_name['err_ctx'].message_type = common__pb2._ERRCTX
DESCRIPTOR.message_types_by_name['EchoReq'] = _ECHOREQ
DESCRIPTOR.message_types_by_name['EchoRsp'] = _ECHORSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EchoReq = _reflection.GeneratedProtocolMessageType('EchoReq', (_message.Message,), dict(
  DESCRIPTOR = _ECHOREQ,
  __module__ = 'cs_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.cs.EchoReq)
  ))
_sym_db.RegisterMessage(EchoReq)

EchoRsp = _reflection.GeneratedProtocolMessageType('EchoRsp', (_message.Message,), dict(
  DESCRIPTOR = _ECHORSP,
  __module__ = 'cs_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.cs.EchoRsp)
  ))
_sym_db.RegisterMessage(EchoRsp)


# @@protoc_insertion_point(module_scope)
