# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cs_msg_id.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cs_msg_id.proto',
  package='com.moon.demo.proto.cs',
  syntax='proto2',
  serialized_pb=_b('\n\x0f\x63s_msg_id.proto\x12\x16\x63om.moon.demo.proto.cs*3\n\x05MsgId\x12\x14\n\x0fMSG_ID_ECHO_REQ\x10\xe8\x07\x12\x14\n\x0fMSG_ID_ECHO_RSP\x10\xe9\x07')
)

_MSGID = _descriptor.EnumDescriptor(
  name='MsgId',
  full_name='com.moon.demo.proto.cs.MsgId',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='MSG_ID_ECHO_REQ', index=0, number=1000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MSG_ID_ECHO_RSP', index=1, number=1001,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=43,
  serialized_end=94,
)
_sym_db.RegisterEnumDescriptor(_MSGID)

MsgId = enum_type_wrapper.EnumTypeWrapper(_MSGID)
MSG_ID_ECHO_REQ = 1000
MSG_ID_ECHO_RSP = 1001


DESCRIPTOR.enum_types_by_name['MsgId'] = _MSGID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
