#ifndef DEMO_SERVER_RAW_TCP_LOCAL_LOGIC_EXPORTER_H_
#define DEMO_SERVER_RAW_TCP_LOCAL_LOGIC_EXPORTER_H_

#include "module_util.h"

MODULE_EXPORTER_DECL();

#endif // DEMO_SERVER_TCP_LOCAL_LOGIC_EXPORTER_H_
