// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_msg.proto

package com.moon.demo.ss;

public final class SsMsg {
  private SsMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GlobalReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.demo.ss.GlobalReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     */
    int getA();

    /**
     * <code>int32 b = 2;</code>
     */
    int getB();
  }
  /**
   * Protobuf type {@code com.moon.demo.ss.GlobalReq}
   */
  public  static final class GlobalReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.demo.ss.GlobalReq)
      GlobalReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GlobalReq.newBuilder() to construct.
    private GlobalReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GlobalReq() {
      a_ = 0;
      b_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              a_ = input.readInt32();
              break;
            }
            case 16: {

              b_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.demo.ss.SsMsg.GlobalReq.class, com.moon.demo.ss.SsMsg.GlobalReq.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int B_FIELD_NUMBER = 2;
    private int b_;
    /**
     * <code>int32 b = 2;</code>
     */
    public int getB() {
      return b_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (b_ != 0) {
        output.writeInt32(2, b_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (b_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, b_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.demo.ss.SsMsg.GlobalReq)) {
        return super.equals(obj);
      }
      com.moon.demo.ss.SsMsg.GlobalReq other = (com.moon.demo.ss.SsMsg.GlobalReq) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && (getB()
          == other.getB());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + B_FIELD_NUMBER;
      hash = (53 * hash) + getB();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.demo.ss.SsMsg.GlobalReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.demo.ss.GlobalReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.demo.ss.GlobalReq)
        com.moon.demo.ss.SsMsg.GlobalReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.demo.ss.SsMsg.GlobalReq.class, com.moon.demo.ss.SsMsg.GlobalReq.Builder.class);
      }

      // Construct using com.moon.demo.ss.SsMsg.GlobalReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        b_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalReq_descriptor;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalReq getDefaultInstanceForType() {
        return com.moon.demo.ss.SsMsg.GlobalReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalReq build() {
        com.moon.demo.ss.SsMsg.GlobalReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalReq buildPartial() {
        com.moon.demo.ss.SsMsg.GlobalReq result = new com.moon.demo.ss.SsMsg.GlobalReq(this);
        result.a_ = a_;
        result.b_ = b_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.demo.ss.SsMsg.GlobalReq) {
          return mergeFrom((com.moon.demo.ss.SsMsg.GlobalReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.demo.ss.SsMsg.GlobalReq other) {
        if (other == com.moon.demo.ss.SsMsg.GlobalReq.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getB() != 0) {
          setB(other.getB());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.demo.ss.SsMsg.GlobalReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.demo.ss.SsMsg.GlobalReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private int b_ ;
      /**
       * <code>int32 b = 2;</code>
       */
      public int getB() {
        return b_;
      }
      /**
       * <code>int32 b = 2;</code>
       */
      public Builder setB(int value) {
        
        b_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 b = 2;</code>
       */
      public Builder clearB() {
        
        b_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.demo.ss.GlobalReq)
    }

    // @@protoc_insertion_point(class_scope:com.moon.demo.ss.GlobalReq)
    private static final com.moon.demo.ss.SsMsg.GlobalReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.demo.ss.SsMsg.GlobalReq();
    }

    public static com.moon.demo.ss.SsMsg.GlobalReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GlobalReq>
        PARSER = new com.google.protobuf.AbstractParser<GlobalReq>() {
      @java.lang.Override
      public GlobalReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GlobalReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.demo.ss.SsMsg.GlobalReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GlobalRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.demo.ss.GlobalRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    boolean hasErrCtx();
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    com.moon.demo.Common.ErrCtx getErrCtx();
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder();
  }
  /**
   * Protobuf type {@code com.moon.demo.ss.GlobalRsp}
   */
  public  static final class GlobalRsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.demo.ss.GlobalRsp)
      GlobalRspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GlobalRsp.newBuilder() to construct.
    private GlobalRsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GlobalRsp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GlobalRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.moon.demo.Common.ErrCtx.Builder subBuilder = null;
              if (errCtx_ != null) {
                subBuilder = errCtx_.toBuilder();
              }
              errCtx_ = input.readMessage(com.moon.demo.Common.ErrCtx.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errCtx_);
                errCtx_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalRsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.demo.ss.SsMsg.GlobalRsp.class, com.moon.demo.ss.SsMsg.GlobalRsp.Builder.class);
    }

    public static final int ERR_CTX_FIELD_NUMBER = 1;
    private com.moon.demo.Common.ErrCtx errCtx_;
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public boolean hasErrCtx() {
      return errCtx_ != null;
    }
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public com.moon.demo.Common.ErrCtx getErrCtx() {
      return errCtx_ == null ? com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
    }
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder() {
      return getErrCtx();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCtx_ != null) {
        output.writeMessage(1, getErrCtx());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCtx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrCtx());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.demo.ss.SsMsg.GlobalRsp)) {
        return super.equals(obj);
      }
      com.moon.demo.ss.SsMsg.GlobalRsp other = (com.moon.demo.ss.SsMsg.GlobalRsp) obj;

      boolean result = true;
      result = result && (hasErrCtx() == other.hasErrCtx());
      if (hasErrCtx()) {
        result = result && getErrCtx()
            .equals(other.getErrCtx());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrCtx()) {
        hash = (37 * hash) + ERR_CTX_FIELD_NUMBER;
        hash = (53 * hash) + getErrCtx().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.GlobalRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.demo.ss.SsMsg.GlobalRsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.demo.ss.GlobalRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.demo.ss.GlobalRsp)
        com.moon.demo.ss.SsMsg.GlobalRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalRsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.demo.ss.SsMsg.GlobalRsp.class, com.moon.demo.ss.SsMsg.GlobalRsp.Builder.class);
      }

      // Construct using com.moon.demo.ss.SsMsg.GlobalRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (errCtxBuilder_ == null) {
          errCtx_ = null;
        } else {
          errCtx_ = null;
          errCtxBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_GlobalRsp_descriptor;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalRsp getDefaultInstanceForType() {
        return com.moon.demo.ss.SsMsg.GlobalRsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalRsp build() {
        com.moon.demo.ss.SsMsg.GlobalRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.GlobalRsp buildPartial() {
        com.moon.demo.ss.SsMsg.GlobalRsp result = new com.moon.demo.ss.SsMsg.GlobalRsp(this);
        if (errCtxBuilder_ == null) {
          result.errCtx_ = errCtx_;
        } else {
          result.errCtx_ = errCtxBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.demo.ss.SsMsg.GlobalRsp) {
          return mergeFrom((com.moon.demo.ss.SsMsg.GlobalRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.demo.ss.SsMsg.GlobalRsp other) {
        if (other == com.moon.demo.ss.SsMsg.GlobalRsp.getDefaultInstance()) return this;
        if (other.hasErrCtx()) {
          mergeErrCtx(other.getErrCtx());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.demo.ss.SsMsg.GlobalRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.demo.ss.SsMsg.GlobalRsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.moon.demo.Common.ErrCtx errCtx_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder> errCtxBuilder_;
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public boolean hasErrCtx() {
        return errCtxBuilder_ != null || errCtx_ != null;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtx getErrCtx() {
        if (errCtxBuilder_ == null) {
          return errCtx_ == null ? com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
        } else {
          return errCtxBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder setErrCtx(com.moon.demo.Common.ErrCtx value) {
        if (errCtxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errCtx_ = value;
          onChanged();
        } else {
          errCtxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder setErrCtx(
          com.moon.demo.Common.ErrCtx.Builder builderForValue) {
        if (errCtxBuilder_ == null) {
          errCtx_ = builderForValue.build();
          onChanged();
        } else {
          errCtxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder mergeErrCtx(com.moon.demo.Common.ErrCtx value) {
        if (errCtxBuilder_ == null) {
          if (errCtx_ != null) {
            errCtx_ =
              com.moon.demo.Common.ErrCtx.newBuilder(errCtx_).mergeFrom(value).buildPartial();
          } else {
            errCtx_ = value;
          }
          onChanged();
        } else {
          errCtxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder clearErrCtx() {
        if (errCtxBuilder_ == null) {
          errCtx_ = null;
          onChanged();
        } else {
          errCtx_ = null;
          errCtxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtx.Builder getErrCtxBuilder() {
        
        onChanged();
        return getErrCtxFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder() {
        if (errCtxBuilder_ != null) {
          return errCtxBuilder_.getMessageOrBuilder();
        } else {
          return errCtx_ == null ?
              com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
        }
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder> 
          getErrCtxFieldBuilder() {
        if (errCtxBuilder_ == null) {
          errCtxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder>(
                  getErrCtx(),
                  getParentForChildren(),
                  isClean());
          errCtx_ = null;
        }
        return errCtxBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.demo.ss.GlobalRsp)
    }

    // @@protoc_insertion_point(class_scope:com.moon.demo.ss.GlobalRsp)
    private static final com.moon.demo.ss.SsMsg.GlobalRsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.demo.ss.SsMsg.GlobalRsp();
    }

    public static com.moon.demo.ss.SsMsg.GlobalRsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GlobalRsp>
        PARSER = new com.google.protobuf.AbstractParser<GlobalRsp>() {
      @java.lang.Override
      public GlobalRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GlobalRsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GlobalRsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GlobalRsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.demo.ss.SsMsg.GlobalRsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Demo1ReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.demo.ss.Demo1Req)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     */
    int getA();

    /**
     * <code>bool udp = 2;</code>
     */
    boolean getUdp();
  }
  /**
   * Protobuf type {@code com.moon.demo.ss.Demo1Req}
   */
  public  static final class Demo1Req extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.demo.ss.Demo1Req)
      Demo1ReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo1Req.newBuilder() to construct.
    private Demo1Req(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo1Req() {
      a_ = 0;
      udp_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo1Req(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              a_ = input.readInt32();
              break;
            }
            case 16: {

              udp_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Req_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Req_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.demo.ss.SsMsg.Demo1Req.class, com.moon.demo.ss.SsMsg.Demo1Req.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    public static final int UDP_FIELD_NUMBER = 2;
    private boolean udp_;
    /**
     * <code>bool udp = 2;</code>
     */
    public boolean getUdp() {
      return udp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      if (udp_ != false) {
        output.writeBool(2, udp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      if (udp_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, udp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.demo.ss.SsMsg.Demo1Req)) {
        return super.equals(obj);
      }
      com.moon.demo.ss.SsMsg.Demo1Req other = (com.moon.demo.ss.SsMsg.Demo1Req) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && (getUdp()
          == other.getUdp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (37 * hash) + UDP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUdp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Req parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.demo.ss.SsMsg.Demo1Req prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.demo.ss.Demo1Req}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.demo.ss.Demo1Req)
        com.moon.demo.ss.SsMsg.Demo1ReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Req_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Req_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.demo.ss.SsMsg.Demo1Req.class, com.moon.demo.ss.SsMsg.Demo1Req.Builder.class);
      }

      // Construct using com.moon.demo.ss.SsMsg.Demo1Req.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        udp_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Req_descriptor;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Req getDefaultInstanceForType() {
        return com.moon.demo.ss.SsMsg.Demo1Req.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Req build() {
        com.moon.demo.ss.SsMsg.Demo1Req result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Req buildPartial() {
        com.moon.demo.ss.SsMsg.Demo1Req result = new com.moon.demo.ss.SsMsg.Demo1Req(this);
        result.a_ = a_;
        result.udp_ = udp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.demo.ss.SsMsg.Demo1Req) {
          return mergeFrom((com.moon.demo.ss.SsMsg.Demo1Req)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.demo.ss.SsMsg.Demo1Req other) {
        if (other == com.moon.demo.ss.SsMsg.Demo1Req.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        if (other.getUdp() != false) {
          setUdp(other.getUdp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.demo.ss.SsMsg.Demo1Req parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.demo.ss.SsMsg.Demo1Req) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }

      private boolean udp_ ;
      /**
       * <code>bool udp = 2;</code>
       */
      public boolean getUdp() {
        return udp_;
      }
      /**
       * <code>bool udp = 2;</code>
       */
      public Builder setUdp(boolean value) {
        
        udp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool udp = 2;</code>
       */
      public Builder clearUdp() {
        
        udp_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.demo.ss.Demo1Req)
    }

    // @@protoc_insertion_point(class_scope:com.moon.demo.ss.Demo1Req)
    private static final com.moon.demo.ss.SsMsg.Demo1Req DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.demo.ss.SsMsg.Demo1Req();
    }

    public static com.moon.demo.ss.SsMsg.Demo1Req getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo1Req>
        PARSER = new com.google.protobuf.AbstractParser<Demo1Req>() {
      @java.lang.Override
      public Demo1Req parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo1Req(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo1Req> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Demo1Req> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.demo.ss.SsMsg.Demo1Req getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Demo1RspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.demo.ss.Demo1Rsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    boolean hasErrCtx();
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    com.moon.demo.Common.ErrCtx getErrCtx();
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder();
  }
  /**
   * Protobuf type {@code com.moon.demo.ss.Demo1Rsp}
   */
  public  static final class Demo1Rsp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.demo.ss.Demo1Rsp)
      Demo1RspOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo1Rsp.newBuilder() to construct.
    private Demo1Rsp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo1Rsp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo1Rsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.moon.demo.Common.ErrCtx.Builder subBuilder = null;
              if (errCtx_ != null) {
                subBuilder = errCtx_.toBuilder();
              }
              errCtx_ = input.readMessage(com.moon.demo.Common.ErrCtx.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(errCtx_);
                errCtx_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Rsp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Rsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.demo.ss.SsMsg.Demo1Rsp.class, com.moon.demo.ss.SsMsg.Demo1Rsp.Builder.class);
    }

    public static final int ERR_CTX_FIELD_NUMBER = 1;
    private com.moon.demo.Common.ErrCtx errCtx_;
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public boolean hasErrCtx() {
      return errCtx_ != null;
    }
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public com.moon.demo.Common.ErrCtx getErrCtx() {
      return errCtx_ == null ? com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
    }
    /**
     * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
     */
    public com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder() {
      return getErrCtx();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (errCtx_ != null) {
        output.writeMessage(1, getErrCtx());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (errCtx_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getErrCtx());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.demo.ss.SsMsg.Demo1Rsp)) {
        return super.equals(obj);
      }
      com.moon.demo.ss.SsMsg.Demo1Rsp other = (com.moon.demo.ss.SsMsg.Demo1Rsp) obj;

      boolean result = true;
      result = result && (hasErrCtx() == other.hasErrCtx());
      if (hasErrCtx()) {
        result = result && getErrCtx()
            .equals(other.getErrCtx());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasErrCtx()) {
        hash = (37 * hash) + ERR_CTX_FIELD_NUMBER;
        hash = (53 * hash) + getErrCtx().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Rsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.demo.ss.SsMsg.Demo1Rsp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.demo.ss.Demo1Rsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.demo.ss.Demo1Rsp)
        com.moon.demo.ss.SsMsg.Demo1RspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Rsp_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Rsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.demo.ss.SsMsg.Demo1Rsp.class, com.moon.demo.ss.SsMsg.Demo1Rsp.Builder.class);
      }

      // Construct using com.moon.demo.ss.SsMsg.Demo1Rsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (errCtxBuilder_ == null) {
          errCtx_ = null;
        } else {
          errCtx_ = null;
          errCtxBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Rsp_descriptor;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Rsp getDefaultInstanceForType() {
        return com.moon.demo.ss.SsMsg.Demo1Rsp.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Rsp build() {
        com.moon.demo.ss.SsMsg.Demo1Rsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Rsp buildPartial() {
        com.moon.demo.ss.SsMsg.Demo1Rsp result = new com.moon.demo.ss.SsMsg.Demo1Rsp(this);
        if (errCtxBuilder_ == null) {
          result.errCtx_ = errCtx_;
        } else {
          result.errCtx_ = errCtxBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.demo.ss.SsMsg.Demo1Rsp) {
          return mergeFrom((com.moon.demo.ss.SsMsg.Demo1Rsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.demo.ss.SsMsg.Demo1Rsp other) {
        if (other == com.moon.demo.ss.SsMsg.Demo1Rsp.getDefaultInstance()) return this;
        if (other.hasErrCtx()) {
          mergeErrCtx(other.getErrCtx());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.demo.ss.SsMsg.Demo1Rsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.demo.ss.SsMsg.Demo1Rsp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.moon.demo.Common.ErrCtx errCtx_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder> errCtxBuilder_;
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public boolean hasErrCtx() {
        return errCtxBuilder_ != null || errCtx_ != null;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtx getErrCtx() {
        if (errCtxBuilder_ == null) {
          return errCtx_ == null ? com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
        } else {
          return errCtxBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder setErrCtx(com.moon.demo.Common.ErrCtx value) {
        if (errCtxBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          errCtx_ = value;
          onChanged();
        } else {
          errCtxBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder setErrCtx(
          com.moon.demo.Common.ErrCtx.Builder builderForValue) {
        if (errCtxBuilder_ == null) {
          errCtx_ = builderForValue.build();
          onChanged();
        } else {
          errCtxBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder mergeErrCtx(com.moon.demo.Common.ErrCtx value) {
        if (errCtxBuilder_ == null) {
          if (errCtx_ != null) {
            errCtx_ =
              com.moon.demo.Common.ErrCtx.newBuilder(errCtx_).mergeFrom(value).buildPartial();
          } else {
            errCtx_ = value;
          }
          onChanged();
        } else {
          errCtxBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public Builder clearErrCtx() {
        if (errCtxBuilder_ == null) {
          errCtx_ = null;
          onChanged();
        } else {
          errCtx_ = null;
          errCtxBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtx.Builder getErrCtxBuilder() {
        
        onChanged();
        return getErrCtxFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      public com.moon.demo.Common.ErrCtxOrBuilder getErrCtxOrBuilder() {
        if (errCtxBuilder_ != null) {
          return errCtxBuilder_.getMessageOrBuilder();
        } else {
          return errCtx_ == null ?
              com.moon.demo.Common.ErrCtx.getDefaultInstance() : errCtx_;
        }
      }
      /**
       * <code>.com.moon.demo.ErrCtx err_ctx = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder> 
          getErrCtxFieldBuilder() {
        if (errCtxBuilder_ == null) {
          errCtxBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.moon.demo.Common.ErrCtx, com.moon.demo.Common.ErrCtx.Builder, com.moon.demo.Common.ErrCtxOrBuilder>(
                  getErrCtx(),
                  getParentForChildren(),
                  isClean());
          errCtx_ = null;
        }
        return errCtxBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.demo.ss.Demo1Rsp)
    }

    // @@protoc_insertion_point(class_scope:com.moon.demo.ss.Demo1Rsp)
    private static final com.moon.demo.ss.SsMsg.Demo1Rsp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.demo.ss.SsMsg.Demo1Rsp();
    }

    public static com.moon.demo.ss.SsMsg.Demo1Rsp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo1Rsp>
        PARSER = new com.google.protobuf.AbstractParser<Demo1Rsp>() {
      @java.lang.Override
      public Demo1Rsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo1Rsp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo1Rsp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Demo1Rsp> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.demo.ss.SsMsg.Demo1Rsp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface Demo1NfyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.demo.ss.Demo1Nfy)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1;</code>
     */
    int getA();
  }
  /**
   * Protobuf type {@code com.moon.demo.ss.Demo1Nfy}
   */
  public  static final class Demo1Nfy extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.demo.ss.Demo1Nfy)
      Demo1NfyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Demo1Nfy.newBuilder() to construct.
    private Demo1Nfy(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Demo1Nfy() {
      a_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Demo1Nfy(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              a_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Nfy_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Nfy_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.demo.ss.SsMsg.Demo1Nfy.class, com.moon.demo.ss.SsMsg.Demo1Nfy.Builder.class);
    }

    public static final int A_FIELD_NUMBER = 1;
    private int a_;
    /**
     * <code>int32 a = 1;</code>
     */
    public int getA() {
      return a_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (a_ != 0) {
        output.writeInt32(1, a_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (a_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, a_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.demo.ss.SsMsg.Demo1Nfy)) {
        return super.equals(obj);
      }
      com.moon.demo.ss.SsMsg.Demo1Nfy other = (com.moon.demo.ss.SsMsg.Demo1Nfy) obj;

      boolean result = true;
      result = result && (getA()
          == other.getA());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + A_FIELD_NUMBER;
      hash = (53 * hash) + getA();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.demo.ss.SsMsg.Demo1Nfy parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.demo.ss.SsMsg.Demo1Nfy prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.demo.ss.Demo1Nfy}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.demo.ss.Demo1Nfy)
        com.moon.demo.ss.SsMsg.Demo1NfyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Nfy_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Nfy_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.demo.ss.SsMsg.Demo1Nfy.class, com.moon.demo.ss.SsMsg.Demo1Nfy.Builder.class);
      }

      // Construct using com.moon.demo.ss.SsMsg.Demo1Nfy.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        a_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.demo.ss.SsMsg.internal_static_com_moon_demo_ss_Demo1Nfy_descriptor;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Nfy getDefaultInstanceForType() {
        return com.moon.demo.ss.SsMsg.Demo1Nfy.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Nfy build() {
        com.moon.demo.ss.SsMsg.Demo1Nfy result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.demo.ss.SsMsg.Demo1Nfy buildPartial() {
        com.moon.demo.ss.SsMsg.Demo1Nfy result = new com.moon.demo.ss.SsMsg.Demo1Nfy(this);
        result.a_ = a_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.demo.ss.SsMsg.Demo1Nfy) {
          return mergeFrom((com.moon.demo.ss.SsMsg.Demo1Nfy)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.demo.ss.SsMsg.Demo1Nfy other) {
        if (other == com.moon.demo.ss.SsMsg.Demo1Nfy.getDefaultInstance()) return this;
        if (other.getA() != 0) {
          setA(other.getA());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.demo.ss.SsMsg.Demo1Nfy parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.demo.ss.SsMsg.Demo1Nfy) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int a_ ;
      /**
       * <code>int32 a = 1;</code>
       */
      public int getA() {
        return a_;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder setA(int value) {
        
        a_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1;</code>
       */
      public Builder clearA() {
        
        a_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.demo.ss.Demo1Nfy)
    }

    // @@protoc_insertion_point(class_scope:com.moon.demo.ss.Demo1Nfy)
    private static final com.moon.demo.ss.SsMsg.Demo1Nfy DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.demo.ss.SsMsg.Demo1Nfy();
    }

    public static com.moon.demo.ss.SsMsg.Demo1Nfy getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Demo1Nfy>
        PARSER = new com.google.protobuf.AbstractParser<Demo1Nfy>() {
      @java.lang.Override
      public Demo1Nfy parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Demo1Nfy(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Demo1Nfy> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Demo1Nfy> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.demo.ss.SsMsg.Demo1Nfy getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_demo_ss_GlobalReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_demo_ss_GlobalReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_demo_ss_GlobalRsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_demo_ss_GlobalRsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_demo_ss_Demo1Req_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_demo_ss_Demo1Req_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_demo_ss_Demo1Rsp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_demo_ss_Demo1Rsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_demo_ss_Demo1Nfy_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_demo_ss_Demo1Nfy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ss_msg.proto\022\020com.moon.demo.ss\032\014common" +
      ".proto\"!\n\tGlobalReq\022\t\n\001a\030\001 \001(\005\022\t\n\001b\030\002 \001(" +
      "\005\"3\n\tGlobalRsp\022&\n\007err_ctx\030\001 \001(\0132\025.com.mo" +
      "on.demo.ErrCtx\"\"\n\010Demo1Req\022\t\n\001a\030\001 \001(\005\022\013\n" +
      "\003udp\030\002 \001(\010\"2\n\010Demo1Rsp\022&\n\007err_ctx\030\001 \001(\0132" +
      "\025.com.moon.demo.ErrCtx\"\025\n\010Demo1Nfy\022\t\n\001a\030" +
      "\001 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.moon.demo.Common.getDescriptor(),
        }, assigner);
    internal_static_com_moon_demo_ss_GlobalReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_moon_demo_ss_GlobalReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_demo_ss_GlobalReq_descriptor,
        new java.lang.String[] { "A", "B", });
    internal_static_com_moon_demo_ss_GlobalRsp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_moon_demo_ss_GlobalRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_demo_ss_GlobalRsp_descriptor,
        new java.lang.String[] { "ErrCtx", });
    internal_static_com_moon_demo_ss_Demo1Req_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_moon_demo_ss_Demo1Req_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_demo_ss_Demo1Req_descriptor,
        new java.lang.String[] { "A", "Udp", });
    internal_static_com_moon_demo_ss_Demo1Rsp_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_moon_demo_ss_Demo1Rsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_demo_ss_Demo1Rsp_descriptor,
        new java.lang.String[] { "ErrCtx", });
    internal_static_com_moon_demo_ss_Demo1Nfy_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_moon_demo_ss_Demo1Nfy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_demo_ss_Demo1Nfy_descriptor,
        new java.lang.String[] { "A", });
    com.moon.demo.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
