// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_msg_id.proto

package com.moon.demo.ss;

public final class SsMsgId {
  private SsMsgId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.moon.demo.ss.MsgID}
   */
  public enum MsgID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLACE_HOLDER = 0;</code>
     */
    PLACE_HOLDER(0),
    /**
     * <code>MSG_ID_DEMO2_REQ = 2000;</code>
     */
    MSG_ID_DEMO2_REQ(2000),
    /**
     * <code>MSG_ID_DEMO2_RSP = 2001;</code>
     */
    MSG_ID_DEMO2_RSP(2001),
    /**
     * <code>MSG_ID_DEMO3_REQ = 2002;</code>
     */
    MSG_ID_DEMO3_REQ(2002),
    /**
     * <code>MSG_ID_DEMO3_RSP = 2003;</code>
     */
    MSG_ID_DEMO3_RSP(2003),
    /**
     * <code>MSG_ID_DEMO4_REQ = 2004;</code>
     */
    MSG_ID_DEMO4_REQ(2004),
    /**
     * <code>MSG_ID_DEMO4_RSP = 2005;</code>
     */
    MSG_ID_DEMO4_RSP(2005),
    /**
     * <code>MSG_ID_DEMO5_REQ = 2006;</code>
     */
    MSG_ID_DEMO5_REQ(2006),
    /**
     * <code>MSG_ID_DEMO5_RSP = 2007;</code>
     */
    MSG_ID_DEMO5_RSP(2007),
    /**
     * <code>MSG_ID_DEMO6_REQ = 2008;</code>
     */
    MSG_ID_DEMO6_REQ(2008),
    /**
     * <code>MSG_ID_DEMO6_RSP = 2009;</code>
     */
    MSG_ID_DEMO6_RSP(2009),
    /**
     * <code>MSG_ID_DEMO7_REQ = 2010;</code>
     */
    MSG_ID_DEMO7_REQ(2010),
    /**
     * <code>MSG_ID_DEMO7_RSP = 2011;</code>
     */
    MSG_ID_DEMO7_RSP(2011),
    /**
     * <code>MSG_ID_DEMO8_REQ = 2012;</code>
     */
    MSG_ID_DEMO8_REQ(2012),
    /**
     * <code>MSG_ID_DEMO8_RSP = 2013;</code>
     */
    MSG_ID_DEMO8_RSP(2013),
    /**
     * <code>MSG_ID_DEMO9_REQ = 2014;</code>
     */
    MSG_ID_DEMO9_REQ(2014),
    /**
     * <code>MSG_ID_DEMO9_RSP = 2015;</code>
     */
    MSG_ID_DEMO9_RSP(2015),
    /**
     * <code>MSG_ID_DEMO10_REQ = 2016;</code>
     */
    MSG_ID_DEMO10_REQ(2016),
    /**
     * <code>MSG_ID_DEMO10_RSP = 2017;</code>
     */
    MSG_ID_DEMO10_RSP(2017),
    /**
     * <code>MSG_ID_DEMO20_REQ = 2018;</code>
     */
    MSG_ID_DEMO20_REQ(2018),
    /**
     * <code>MSG_ID_DEMO20_RSP = 2019;</code>
     */
    MSG_ID_DEMO20_RSP(2019),
    /**
     * <code>MSG_ID_DEMO50_REQ = 2020;</code>
     */
    MSG_ID_DEMO50_REQ(2020),
    /**
     * <code>MSG_ID_DEMO50_RSP = 2021;</code>
     */
    MSG_ID_DEMO50_RSP(2021),
    /**
     * <code>MSG_ID_DEMO90_REQ = 2022;</code>
     */
    MSG_ID_DEMO90_REQ(2022),
    /**
     * <code>MSG_ID_DEMO90_RSP = 2023;</code>
     */
    MSG_ID_DEMO90_RSP(2023),
    /**
     * <code>MSG_ID_DEMO2_NFY = 2024;</code>
     */
    MSG_ID_DEMO2_NFY(2024),
    /**
     * <code>MSG_ID_DEMO5_NFY = 2025;</code>
     */
    MSG_ID_DEMO5_NFY(2025),
    /**
     * <code>MSG_ID_DEMO9_NFY = 2026;</code>
     */
    MSG_ID_DEMO9_NFY(2026),
    /**
     * <code>MSG_ID_DEMO301_REQ = 2027;</code>
     */
    MSG_ID_DEMO301_REQ(2027),
    /**
     * <code>MSG_ID_DEMO301_RSP = 2028;</code>
     */
    MSG_ID_DEMO301_RSP(2028),
    /**
     * <code>MSG_ID_DEMO301_NFY = 2029;</code>
     */
    MSG_ID_DEMO301_NFY(2029),
    /**
     * <code>MSG_ID_DEMO302_REQ = 2030;</code>
     */
    MSG_ID_DEMO302_REQ(2030),
    /**
     * <code>MSG_ID_DEMO302_RSP = 2031;</code>
     */
    MSG_ID_DEMO302_RSP(2031),
    /**
     * <code>MSG_ID_DEMO303_REQ = 2032;</code>
     */
    MSG_ID_DEMO303_REQ(2032),
    /**
     * <code>MSG_ID_DEMO303_RSP = 2033;</code>
     */
    MSG_ID_DEMO303_RSP(2033),
    /**
     * <code>MSG_ID_DEMO1002_REQ = 2034;</code>
     */
    MSG_ID_DEMO1002_REQ(2034),
    /**
     * <code>MSG_ID_DEMO1002_RSP = 2035;</code>
     */
    MSG_ID_DEMO1002_RSP(2035),
    /**
     * <code>MSG_ID_DEMO1003_REQ = 2036;</code>
     */
    MSG_ID_DEMO1003_REQ(2036),
    /**
     * <code>MSG_ID_DEMO1003_RSP = 2037;</code>
     */
    MSG_ID_DEMO1003_RSP(2037),
    /**
     * <code>MSG_ID_DEMO1004_REQ = 2038;</code>
     */
    MSG_ID_DEMO1004_REQ(2038),
    /**
     * <code>MSG_ID_DEMO1004_RSP = 2039;</code>
     */
    MSG_ID_DEMO1004_RSP(2039),
    /**
     * <code>MSG_ID_DEMO1005_REQ = 2040;</code>
     */
    MSG_ID_DEMO1005_REQ(2040),
    /**
     * <code>MSG_ID_DEMO1005_RSP = 2041;</code>
     */
    MSG_ID_DEMO1005_RSP(2041),
    /**
     * <code>MSG_ID_DEMO1006_REQ = 2042;</code>
     */
    MSG_ID_DEMO1006_REQ(2042),
    /**
     * <code>MSG_ID_DEMO1006_RSP = 2043;</code>
     */
    MSG_ID_DEMO1006_RSP(2043),
    /**
     * <code>MSG_ID_DEMO1007_REQ = 2044;</code>
     */
    MSG_ID_DEMO1007_REQ(2044),
    /**
     * <code>MSG_ID_DEMO1007_RSP = 2045;</code>
     */
    MSG_ID_DEMO1007_RSP(2045),
    /**
     * <code>MSG_ID_DEMO1008_REQ = 2046;</code>
     */
    MSG_ID_DEMO1008_REQ(2046),
    /**
     * <code>MSG_ID_DEMO1008_RSP = 2047;</code>
     */
    MSG_ID_DEMO1008_RSP(2047),
    /**
     * <code>MSG_ID_DEMO1009_REQ = 2048;</code>
     */
    MSG_ID_DEMO1009_REQ(2048),
    /**
     * <code>MSG_ID_DEMO1009_RSP = 2049;</code>
     */
    MSG_ID_DEMO1009_RSP(2049),
    /**
     * <code>MSG_ID_DEMO1010_REQ = 2050;</code>
     */
    MSG_ID_DEMO1010_REQ(2050),
    /**
     * <code>MSG_ID_DEMO1010_RSP = 2051;</code>
     */
    MSG_ID_DEMO1010_RSP(2051),
    /**
     * <code>MSG_ID_DEMO1020_REQ = 2052;</code>
     */
    MSG_ID_DEMO1020_REQ(2052),
    /**
     * <code>MSG_ID_DEMO1020_RSP = 2053;</code>
     */
    MSG_ID_DEMO1020_RSP(2053),
    /**
     * <code>MSG_ID_DEMO1050_REQ = 2054;</code>
     */
    MSG_ID_DEMO1050_REQ(2054),
    /**
     * <code>MSG_ID_DEMO1050_RSP = 2055;</code>
     */
    MSG_ID_DEMO1050_RSP(2055),
    /**
     * <code>MSG_ID_DEMO1090_REQ = 2056;</code>
     */
    MSG_ID_DEMO1090_REQ(2056),
    /**
     * <code>MSG_ID_DEMO1090_RSP = 2057;</code>
     */
    MSG_ID_DEMO1090_RSP(2057),
    /**
     * <code>MSG_ID_DEMO1002_NFY = 2058;</code>
     */
    MSG_ID_DEMO1002_NFY(2058),
    /**
     * <code>MSG_ID_DEMO1005_NFY = 2059;</code>
     */
    MSG_ID_DEMO1005_NFY(2059),
    /**
     * <code>MSG_ID_DEMO1009_NFY = 2060;</code>
     */
    MSG_ID_DEMO1009_NFY(2060),
    /**
     * <code>MSG_ID_DEMO2002_REQ = 2061;</code>
     */
    MSG_ID_DEMO2002_REQ(2061),
    /**
     * <code>MSG_ID_DEMO2002_RSP = 2062;</code>
     */
    MSG_ID_DEMO2002_RSP(2062),
    /**
     * <code>MSG_ID_DEMO2003_REQ = 2063;</code>
     */
    MSG_ID_DEMO2003_REQ(2063),
    /**
     * <code>MSG_ID_DEMO2003_RSP = 2064;</code>
     */
    MSG_ID_DEMO2003_RSP(2064),
    /**
     * <code>MSG_ID_DEMO2004_REQ = 2065;</code>
     */
    MSG_ID_DEMO2004_REQ(2065),
    /**
     * <code>MSG_ID_DEMO2004_RSP = 2066;</code>
     */
    MSG_ID_DEMO2004_RSP(2066),
    /**
     * <code>MSG_ID_DEMO2005_REQ = 2067;</code>
     */
    MSG_ID_DEMO2005_REQ(2067),
    /**
     * <code>MSG_ID_DEMO2005_RSP = 2068;</code>
     */
    MSG_ID_DEMO2005_RSP(2068),
    /**
     * <code>MSG_ID_DEMO2006_REQ = 2069;</code>
     */
    MSG_ID_DEMO2006_REQ(2069),
    /**
     * <code>MSG_ID_DEMO2006_RSP = 2070;</code>
     */
    MSG_ID_DEMO2006_RSP(2070),
    /**
     * <code>MSG_ID_DEMO2007_REQ = 2071;</code>
     */
    MSG_ID_DEMO2007_REQ(2071),
    /**
     * <code>MSG_ID_DEMO2007_RSP = 2072;</code>
     */
    MSG_ID_DEMO2007_RSP(2072),
    /**
     * <code>MSG_ID_DEMO2008_REQ = 2073;</code>
     */
    MSG_ID_DEMO2008_REQ(2073),
    /**
     * <code>MSG_ID_DEMO2008_RSP = 2074;</code>
     */
    MSG_ID_DEMO2008_RSP(2074),
    /**
     * <code>MSG_ID_DEMO2009_REQ = 2075;</code>
     */
    MSG_ID_DEMO2009_REQ(2075),
    /**
     * <code>MSG_ID_DEMO2009_RSP = 2076;</code>
     */
    MSG_ID_DEMO2009_RSP(2076),
    /**
     * <code>MSG_ID_DEMO2010_REQ = 2077;</code>
     */
    MSG_ID_DEMO2010_REQ(2077),
    /**
     * <code>MSG_ID_DEMO2010_RSP = 2078;</code>
     */
    MSG_ID_DEMO2010_RSP(2078),
    /**
     * <code>MSG_ID_DEMO2020_REQ = 2079;</code>
     */
    MSG_ID_DEMO2020_REQ(2079),
    /**
     * <code>MSG_ID_DEMO2020_RSP = 2080;</code>
     */
    MSG_ID_DEMO2020_RSP(2080),
    /**
     * <code>MSG_ID_DEMO2050_REQ = 2081;</code>
     */
    MSG_ID_DEMO2050_REQ(2081),
    /**
     * <code>MSG_ID_DEMO2050_RSP = 2082;</code>
     */
    MSG_ID_DEMO2050_RSP(2082),
    /**
     * <code>MSG_ID_DEMO2090_REQ = 2083;</code>
     */
    MSG_ID_DEMO2090_REQ(2083),
    /**
     * <code>MSG_ID_DEMO2090_RSP = 2084;</code>
     */
    MSG_ID_DEMO2090_RSP(2084),
    /**
     * <code>MSG_ID_DEMO2002_NFY = 2085;</code>
     */
    MSG_ID_DEMO2002_NFY(2085),
    /**
     * <code>MSG_ID_DEMO2005_NFY = 2086;</code>
     */
    MSG_ID_DEMO2005_NFY(2086),
    /**
     * <code>MSG_ID_DEMO2009_NFY = 2087;</code>
     */
    MSG_ID_DEMO2009_NFY(2087),
    /**
     * <code>MSG_ID_DEMO3002_REQ = 2088;</code>
     */
    MSG_ID_DEMO3002_REQ(2088),
    /**
     * <code>MSG_ID_DEMO3002_RSP = 2089;</code>
     */
    MSG_ID_DEMO3002_RSP(2089),
    /**
     * <code>MSG_ID_DEMO3003_REQ = 2090;</code>
     */
    MSG_ID_DEMO3003_REQ(2090),
    /**
     * <code>MSG_ID_DEMO3003_RSP = 2091;</code>
     */
    MSG_ID_DEMO3003_RSP(2091),
    /**
     * <code>MSG_ID_DEMO3004_REQ = 2092;</code>
     */
    MSG_ID_DEMO3004_REQ(2092),
    /**
     * <code>MSG_ID_DEMO3004_RSP = 2093;</code>
     */
    MSG_ID_DEMO3004_RSP(2093),
    /**
     * <code>MSG_ID_DEMO3005_REQ = 2094;</code>
     */
    MSG_ID_DEMO3005_REQ(2094),
    /**
     * <code>MSG_ID_DEMO3005_RSP = 2095;</code>
     */
    MSG_ID_DEMO3005_RSP(2095),
    /**
     * <code>MSG_ID_DEMO3006_REQ = 2096;</code>
     */
    MSG_ID_DEMO3006_REQ(2096),
    /**
     * <code>MSG_ID_DEMO3006_RSP = 2097;</code>
     */
    MSG_ID_DEMO3006_RSP(2097),
    /**
     * <code>MSG_ID_DEMO3007_REQ = 2098;</code>
     */
    MSG_ID_DEMO3007_REQ(2098),
    /**
     * <code>MSG_ID_DEMO3007_RSP = 2099;</code>
     */
    MSG_ID_DEMO3007_RSP(2099),
    /**
     * <code>MSG_ID_DEMO3008_REQ = 2100;</code>
     */
    MSG_ID_DEMO3008_REQ(2100),
    /**
     * <code>MSG_ID_DEMO3008_RSP = 2101;</code>
     */
    MSG_ID_DEMO3008_RSP(2101),
    /**
     * <code>MSG_ID_DEMO3009_REQ = 2102;</code>
     */
    MSG_ID_DEMO3009_REQ(2102),
    /**
     * <code>MSG_ID_DEMO3009_RSP = 2103;</code>
     */
    MSG_ID_DEMO3009_RSP(2103),
    /**
     * <code>MSG_ID_DEMO3010_REQ = 2104;</code>
     */
    MSG_ID_DEMO3010_REQ(2104),
    /**
     * <code>MSG_ID_DEMO3010_RSP = 2105;</code>
     */
    MSG_ID_DEMO3010_RSP(2105),
    /**
     * <code>MSG_ID_DEMO3020_REQ = 2106;</code>
     */
    MSG_ID_DEMO3020_REQ(2106),
    /**
     * <code>MSG_ID_DEMO3020_RSP = 2107;</code>
     */
    MSG_ID_DEMO3020_RSP(2107),
    /**
     * <code>MSG_ID_DEMO3050_REQ = 2108;</code>
     */
    MSG_ID_DEMO3050_REQ(2108),
    /**
     * <code>MSG_ID_DEMO3050_RSP = 2109;</code>
     */
    MSG_ID_DEMO3050_RSP(2109),
    /**
     * <code>MSG_ID_DEMO3090_REQ = 2110;</code>
     */
    MSG_ID_DEMO3090_REQ(2110),
    /**
     * <code>MSG_ID_DEMO3090_RSP = 2111;</code>
     */
    MSG_ID_DEMO3090_RSP(2111),
    /**
     * <code>MSG_ID_DEMO3002_NFY = 2112;</code>
     */
    MSG_ID_DEMO3002_NFY(2112),
    /**
     * <code>MSG_ID_DEMO3005_NFY = 2113;</code>
     */
    MSG_ID_DEMO3005_NFY(2113),
    /**
     * <code>MSG_ID_DEMO3009_NFY = 2114;</code>
     */
    MSG_ID_DEMO3009_NFY(2114),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLACE_HOLDER = 0;</code>
     */
    public static final int PLACE_HOLDER_VALUE = 0;
    /**
     * <code>MSG_ID_DEMO2_REQ = 2000;</code>
     */
    public static final int MSG_ID_DEMO2_REQ_VALUE = 2000;
    /**
     * <code>MSG_ID_DEMO2_RSP = 2001;</code>
     */
    public static final int MSG_ID_DEMO2_RSP_VALUE = 2001;
    /**
     * <code>MSG_ID_DEMO3_REQ = 2002;</code>
     */
    public static final int MSG_ID_DEMO3_REQ_VALUE = 2002;
    /**
     * <code>MSG_ID_DEMO3_RSP = 2003;</code>
     */
    public static final int MSG_ID_DEMO3_RSP_VALUE = 2003;
    /**
     * <code>MSG_ID_DEMO4_REQ = 2004;</code>
     */
    public static final int MSG_ID_DEMO4_REQ_VALUE = 2004;
    /**
     * <code>MSG_ID_DEMO4_RSP = 2005;</code>
     */
    public static final int MSG_ID_DEMO4_RSP_VALUE = 2005;
    /**
     * <code>MSG_ID_DEMO5_REQ = 2006;</code>
     */
    public static final int MSG_ID_DEMO5_REQ_VALUE = 2006;
    /**
     * <code>MSG_ID_DEMO5_RSP = 2007;</code>
     */
    public static final int MSG_ID_DEMO5_RSP_VALUE = 2007;
    /**
     * <code>MSG_ID_DEMO6_REQ = 2008;</code>
     */
    public static final int MSG_ID_DEMO6_REQ_VALUE = 2008;
    /**
     * <code>MSG_ID_DEMO6_RSP = 2009;</code>
     */
    public static final int MSG_ID_DEMO6_RSP_VALUE = 2009;
    /**
     * <code>MSG_ID_DEMO7_REQ = 2010;</code>
     */
    public static final int MSG_ID_DEMO7_REQ_VALUE = 2010;
    /**
     * <code>MSG_ID_DEMO7_RSP = 2011;</code>
     */
    public static final int MSG_ID_DEMO7_RSP_VALUE = 2011;
    /**
     * <code>MSG_ID_DEMO8_REQ = 2012;</code>
     */
    public static final int MSG_ID_DEMO8_REQ_VALUE = 2012;
    /**
     * <code>MSG_ID_DEMO8_RSP = 2013;</code>
     */
    public static final int MSG_ID_DEMO8_RSP_VALUE = 2013;
    /**
     * <code>MSG_ID_DEMO9_REQ = 2014;</code>
     */
    public static final int MSG_ID_DEMO9_REQ_VALUE = 2014;
    /**
     * <code>MSG_ID_DEMO9_RSP = 2015;</code>
     */
    public static final int MSG_ID_DEMO9_RSP_VALUE = 2015;
    /**
     * <code>MSG_ID_DEMO10_REQ = 2016;</code>
     */
    public static final int MSG_ID_DEMO10_REQ_VALUE = 2016;
    /**
     * <code>MSG_ID_DEMO10_RSP = 2017;</code>
     */
    public static final int MSG_ID_DEMO10_RSP_VALUE = 2017;
    /**
     * <code>MSG_ID_DEMO20_REQ = 2018;</code>
     */
    public static final int MSG_ID_DEMO20_REQ_VALUE = 2018;
    /**
     * <code>MSG_ID_DEMO20_RSP = 2019;</code>
     */
    public static final int MSG_ID_DEMO20_RSP_VALUE = 2019;
    /**
     * <code>MSG_ID_DEMO50_REQ = 2020;</code>
     */
    public static final int MSG_ID_DEMO50_REQ_VALUE = 2020;
    /**
     * <code>MSG_ID_DEMO50_RSP = 2021;</code>
     */
    public static final int MSG_ID_DEMO50_RSP_VALUE = 2021;
    /**
     * <code>MSG_ID_DEMO90_REQ = 2022;</code>
     */
    public static final int MSG_ID_DEMO90_REQ_VALUE = 2022;
    /**
     * <code>MSG_ID_DEMO90_RSP = 2023;</code>
     */
    public static final int MSG_ID_DEMO90_RSP_VALUE = 2023;
    /**
     * <code>MSG_ID_DEMO2_NFY = 2024;</code>
     */
    public static final int MSG_ID_DEMO2_NFY_VALUE = 2024;
    /**
     * <code>MSG_ID_DEMO5_NFY = 2025;</code>
     */
    public static final int MSG_ID_DEMO5_NFY_VALUE = 2025;
    /**
     * <code>MSG_ID_DEMO9_NFY = 2026;</code>
     */
    public static final int MSG_ID_DEMO9_NFY_VALUE = 2026;
    /**
     * <code>MSG_ID_DEMO301_REQ = 2027;</code>
     */
    public static final int MSG_ID_DEMO301_REQ_VALUE = 2027;
    /**
     * <code>MSG_ID_DEMO301_RSP = 2028;</code>
     */
    public static final int MSG_ID_DEMO301_RSP_VALUE = 2028;
    /**
     * <code>MSG_ID_DEMO301_NFY = 2029;</code>
     */
    public static final int MSG_ID_DEMO301_NFY_VALUE = 2029;
    /**
     * <code>MSG_ID_DEMO302_REQ = 2030;</code>
     */
    public static final int MSG_ID_DEMO302_REQ_VALUE = 2030;
    /**
     * <code>MSG_ID_DEMO302_RSP = 2031;</code>
     */
    public static final int MSG_ID_DEMO302_RSP_VALUE = 2031;
    /**
     * <code>MSG_ID_DEMO303_REQ = 2032;</code>
     */
    public static final int MSG_ID_DEMO303_REQ_VALUE = 2032;
    /**
     * <code>MSG_ID_DEMO303_RSP = 2033;</code>
     */
    public static final int MSG_ID_DEMO303_RSP_VALUE = 2033;
    /**
     * <code>MSG_ID_DEMO1002_REQ = 2034;</code>
     */
    public static final int MSG_ID_DEMO1002_REQ_VALUE = 2034;
    /**
     * <code>MSG_ID_DEMO1002_RSP = 2035;</code>
     */
    public static final int MSG_ID_DEMO1002_RSP_VALUE = 2035;
    /**
     * <code>MSG_ID_DEMO1003_REQ = 2036;</code>
     */
    public static final int MSG_ID_DEMO1003_REQ_VALUE = 2036;
    /**
     * <code>MSG_ID_DEMO1003_RSP = 2037;</code>
     */
    public static final int MSG_ID_DEMO1003_RSP_VALUE = 2037;
    /**
     * <code>MSG_ID_DEMO1004_REQ = 2038;</code>
     */
    public static final int MSG_ID_DEMO1004_REQ_VALUE = 2038;
    /**
     * <code>MSG_ID_DEMO1004_RSP = 2039;</code>
     */
    public static final int MSG_ID_DEMO1004_RSP_VALUE = 2039;
    /**
     * <code>MSG_ID_DEMO1005_REQ = 2040;</code>
     */
    public static final int MSG_ID_DEMO1005_REQ_VALUE = 2040;
    /**
     * <code>MSG_ID_DEMO1005_RSP = 2041;</code>
     */
    public static final int MSG_ID_DEMO1005_RSP_VALUE = 2041;
    /**
     * <code>MSG_ID_DEMO1006_REQ = 2042;</code>
     */
    public static final int MSG_ID_DEMO1006_REQ_VALUE = 2042;
    /**
     * <code>MSG_ID_DEMO1006_RSP = 2043;</code>
     */
    public static final int MSG_ID_DEMO1006_RSP_VALUE = 2043;
    /**
     * <code>MSG_ID_DEMO1007_REQ = 2044;</code>
     */
    public static final int MSG_ID_DEMO1007_REQ_VALUE = 2044;
    /**
     * <code>MSG_ID_DEMO1007_RSP = 2045;</code>
     */
    public static final int MSG_ID_DEMO1007_RSP_VALUE = 2045;
    /**
     * <code>MSG_ID_DEMO1008_REQ = 2046;</code>
     */
    public static final int MSG_ID_DEMO1008_REQ_VALUE = 2046;
    /**
     * <code>MSG_ID_DEMO1008_RSP = 2047;</code>
     */
    public static final int MSG_ID_DEMO1008_RSP_VALUE = 2047;
    /**
     * <code>MSG_ID_DEMO1009_REQ = 2048;</code>
     */
    public static final int MSG_ID_DEMO1009_REQ_VALUE = 2048;
    /**
     * <code>MSG_ID_DEMO1009_RSP = 2049;</code>
     */
    public static final int MSG_ID_DEMO1009_RSP_VALUE = 2049;
    /**
     * <code>MSG_ID_DEMO1010_REQ = 2050;</code>
     */
    public static final int MSG_ID_DEMO1010_REQ_VALUE = 2050;
    /**
     * <code>MSG_ID_DEMO1010_RSP = 2051;</code>
     */
    public static final int MSG_ID_DEMO1010_RSP_VALUE = 2051;
    /**
     * <code>MSG_ID_DEMO1020_REQ = 2052;</code>
     */
    public static final int MSG_ID_DEMO1020_REQ_VALUE = 2052;
    /**
     * <code>MSG_ID_DEMO1020_RSP = 2053;</code>
     */
    public static final int MSG_ID_DEMO1020_RSP_VALUE = 2053;
    /**
     * <code>MSG_ID_DEMO1050_REQ = 2054;</code>
     */
    public static final int MSG_ID_DEMO1050_REQ_VALUE = 2054;
    /**
     * <code>MSG_ID_DEMO1050_RSP = 2055;</code>
     */
    public static final int MSG_ID_DEMO1050_RSP_VALUE = 2055;
    /**
     * <code>MSG_ID_DEMO1090_REQ = 2056;</code>
     */
    public static final int MSG_ID_DEMO1090_REQ_VALUE = 2056;
    /**
     * <code>MSG_ID_DEMO1090_RSP = 2057;</code>
     */
    public static final int MSG_ID_DEMO1090_RSP_VALUE = 2057;
    /**
     * <code>MSG_ID_DEMO1002_NFY = 2058;</code>
     */
    public static final int MSG_ID_DEMO1002_NFY_VALUE = 2058;
    /**
     * <code>MSG_ID_DEMO1005_NFY = 2059;</code>
     */
    public static final int MSG_ID_DEMO1005_NFY_VALUE = 2059;
    /**
     * <code>MSG_ID_DEMO1009_NFY = 2060;</code>
     */
    public static final int MSG_ID_DEMO1009_NFY_VALUE = 2060;
    /**
     * <code>MSG_ID_DEMO2002_REQ = 2061;</code>
     */
    public static final int MSG_ID_DEMO2002_REQ_VALUE = 2061;
    /**
     * <code>MSG_ID_DEMO2002_RSP = 2062;</code>
     */
    public static final int MSG_ID_DEMO2002_RSP_VALUE = 2062;
    /**
     * <code>MSG_ID_DEMO2003_REQ = 2063;</code>
     */
    public static final int MSG_ID_DEMO2003_REQ_VALUE = 2063;
    /**
     * <code>MSG_ID_DEMO2003_RSP = 2064;</code>
     */
    public static final int MSG_ID_DEMO2003_RSP_VALUE = 2064;
    /**
     * <code>MSG_ID_DEMO2004_REQ = 2065;</code>
     */
    public static final int MSG_ID_DEMO2004_REQ_VALUE = 2065;
    /**
     * <code>MSG_ID_DEMO2004_RSP = 2066;</code>
     */
    public static final int MSG_ID_DEMO2004_RSP_VALUE = 2066;
    /**
     * <code>MSG_ID_DEMO2005_REQ = 2067;</code>
     */
    public static final int MSG_ID_DEMO2005_REQ_VALUE = 2067;
    /**
     * <code>MSG_ID_DEMO2005_RSP = 2068;</code>
     */
    public static final int MSG_ID_DEMO2005_RSP_VALUE = 2068;
    /**
     * <code>MSG_ID_DEMO2006_REQ = 2069;</code>
     */
    public static final int MSG_ID_DEMO2006_REQ_VALUE = 2069;
    /**
     * <code>MSG_ID_DEMO2006_RSP = 2070;</code>
     */
    public static final int MSG_ID_DEMO2006_RSP_VALUE = 2070;
    /**
     * <code>MSG_ID_DEMO2007_REQ = 2071;</code>
     */
    public static final int MSG_ID_DEMO2007_REQ_VALUE = 2071;
    /**
     * <code>MSG_ID_DEMO2007_RSP = 2072;</code>
     */
    public static final int MSG_ID_DEMO2007_RSP_VALUE = 2072;
    /**
     * <code>MSG_ID_DEMO2008_REQ = 2073;</code>
     */
    public static final int MSG_ID_DEMO2008_REQ_VALUE = 2073;
    /**
     * <code>MSG_ID_DEMO2008_RSP = 2074;</code>
     */
    public static final int MSG_ID_DEMO2008_RSP_VALUE = 2074;
    /**
     * <code>MSG_ID_DEMO2009_REQ = 2075;</code>
     */
    public static final int MSG_ID_DEMO2009_REQ_VALUE = 2075;
    /**
     * <code>MSG_ID_DEMO2009_RSP = 2076;</code>
     */
    public static final int MSG_ID_DEMO2009_RSP_VALUE = 2076;
    /**
     * <code>MSG_ID_DEMO2010_REQ = 2077;</code>
     */
    public static final int MSG_ID_DEMO2010_REQ_VALUE = 2077;
    /**
     * <code>MSG_ID_DEMO2010_RSP = 2078;</code>
     */
    public static final int MSG_ID_DEMO2010_RSP_VALUE = 2078;
    /**
     * <code>MSG_ID_DEMO2020_REQ = 2079;</code>
     */
    public static final int MSG_ID_DEMO2020_REQ_VALUE = 2079;
    /**
     * <code>MSG_ID_DEMO2020_RSP = 2080;</code>
     */
    public static final int MSG_ID_DEMO2020_RSP_VALUE = 2080;
    /**
     * <code>MSG_ID_DEMO2050_REQ = 2081;</code>
     */
    public static final int MSG_ID_DEMO2050_REQ_VALUE = 2081;
    /**
     * <code>MSG_ID_DEMO2050_RSP = 2082;</code>
     */
    public static final int MSG_ID_DEMO2050_RSP_VALUE = 2082;
    /**
     * <code>MSG_ID_DEMO2090_REQ = 2083;</code>
     */
    public static final int MSG_ID_DEMO2090_REQ_VALUE = 2083;
    /**
     * <code>MSG_ID_DEMO2090_RSP = 2084;</code>
     */
    public static final int MSG_ID_DEMO2090_RSP_VALUE = 2084;
    /**
     * <code>MSG_ID_DEMO2002_NFY = 2085;</code>
     */
    public static final int MSG_ID_DEMO2002_NFY_VALUE = 2085;
    /**
     * <code>MSG_ID_DEMO2005_NFY = 2086;</code>
     */
    public static final int MSG_ID_DEMO2005_NFY_VALUE = 2086;
    /**
     * <code>MSG_ID_DEMO2009_NFY = 2087;</code>
     */
    public static final int MSG_ID_DEMO2009_NFY_VALUE = 2087;
    /**
     * <code>MSG_ID_DEMO3002_REQ = 2088;</code>
     */
    public static final int MSG_ID_DEMO3002_REQ_VALUE = 2088;
    /**
     * <code>MSG_ID_DEMO3002_RSP = 2089;</code>
     */
    public static final int MSG_ID_DEMO3002_RSP_VALUE = 2089;
    /**
     * <code>MSG_ID_DEMO3003_REQ = 2090;</code>
     */
    public static final int MSG_ID_DEMO3003_REQ_VALUE = 2090;
    /**
     * <code>MSG_ID_DEMO3003_RSP = 2091;</code>
     */
    public static final int MSG_ID_DEMO3003_RSP_VALUE = 2091;
    /**
     * <code>MSG_ID_DEMO3004_REQ = 2092;</code>
     */
    public static final int MSG_ID_DEMO3004_REQ_VALUE = 2092;
    /**
     * <code>MSG_ID_DEMO3004_RSP = 2093;</code>
     */
    public static final int MSG_ID_DEMO3004_RSP_VALUE = 2093;
    /**
     * <code>MSG_ID_DEMO3005_REQ = 2094;</code>
     */
    public static final int MSG_ID_DEMO3005_REQ_VALUE = 2094;
    /**
     * <code>MSG_ID_DEMO3005_RSP = 2095;</code>
     */
    public static final int MSG_ID_DEMO3005_RSP_VALUE = 2095;
    /**
     * <code>MSG_ID_DEMO3006_REQ = 2096;</code>
     */
    public static final int MSG_ID_DEMO3006_REQ_VALUE = 2096;
    /**
     * <code>MSG_ID_DEMO3006_RSP = 2097;</code>
     */
    public static final int MSG_ID_DEMO3006_RSP_VALUE = 2097;
    /**
     * <code>MSG_ID_DEMO3007_REQ = 2098;</code>
     */
    public static final int MSG_ID_DEMO3007_REQ_VALUE = 2098;
    /**
     * <code>MSG_ID_DEMO3007_RSP = 2099;</code>
     */
    public static final int MSG_ID_DEMO3007_RSP_VALUE = 2099;
    /**
     * <code>MSG_ID_DEMO3008_REQ = 2100;</code>
     */
    public static final int MSG_ID_DEMO3008_REQ_VALUE = 2100;
    /**
     * <code>MSG_ID_DEMO3008_RSP = 2101;</code>
     */
    public static final int MSG_ID_DEMO3008_RSP_VALUE = 2101;
    /**
     * <code>MSG_ID_DEMO3009_REQ = 2102;</code>
     */
    public static final int MSG_ID_DEMO3009_REQ_VALUE = 2102;
    /**
     * <code>MSG_ID_DEMO3009_RSP = 2103;</code>
     */
    public static final int MSG_ID_DEMO3009_RSP_VALUE = 2103;
    /**
     * <code>MSG_ID_DEMO3010_REQ = 2104;</code>
     */
    public static final int MSG_ID_DEMO3010_REQ_VALUE = 2104;
    /**
     * <code>MSG_ID_DEMO3010_RSP = 2105;</code>
     */
    public static final int MSG_ID_DEMO3010_RSP_VALUE = 2105;
    /**
     * <code>MSG_ID_DEMO3020_REQ = 2106;</code>
     */
    public static final int MSG_ID_DEMO3020_REQ_VALUE = 2106;
    /**
     * <code>MSG_ID_DEMO3020_RSP = 2107;</code>
     */
    public static final int MSG_ID_DEMO3020_RSP_VALUE = 2107;
    /**
     * <code>MSG_ID_DEMO3050_REQ = 2108;</code>
     */
    public static final int MSG_ID_DEMO3050_REQ_VALUE = 2108;
    /**
     * <code>MSG_ID_DEMO3050_RSP = 2109;</code>
     */
    public static final int MSG_ID_DEMO3050_RSP_VALUE = 2109;
    /**
     * <code>MSG_ID_DEMO3090_REQ = 2110;</code>
     */
    public static final int MSG_ID_DEMO3090_REQ_VALUE = 2110;
    /**
     * <code>MSG_ID_DEMO3090_RSP = 2111;</code>
     */
    public static final int MSG_ID_DEMO3090_RSP_VALUE = 2111;
    /**
     * <code>MSG_ID_DEMO3002_NFY = 2112;</code>
     */
    public static final int MSG_ID_DEMO3002_NFY_VALUE = 2112;
    /**
     * <code>MSG_ID_DEMO3005_NFY = 2113;</code>
     */
    public static final int MSG_ID_DEMO3005_NFY_VALUE = 2113;
    /**
     * <code>MSG_ID_DEMO3009_NFY = 2114;</code>
     */
    public static final int MSG_ID_DEMO3009_NFY_VALUE = 2114;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgID valueOf(int value) {
      return forNumber(value);
    }

    public static MsgID forNumber(int value) {
      switch (value) {
        case 0: return PLACE_HOLDER;
        case 2000: return MSG_ID_DEMO2_REQ;
        case 2001: return MSG_ID_DEMO2_RSP;
        case 2002: return MSG_ID_DEMO3_REQ;
        case 2003: return MSG_ID_DEMO3_RSP;
        case 2004: return MSG_ID_DEMO4_REQ;
        case 2005: return MSG_ID_DEMO4_RSP;
        case 2006: return MSG_ID_DEMO5_REQ;
        case 2007: return MSG_ID_DEMO5_RSP;
        case 2008: return MSG_ID_DEMO6_REQ;
        case 2009: return MSG_ID_DEMO6_RSP;
        case 2010: return MSG_ID_DEMO7_REQ;
        case 2011: return MSG_ID_DEMO7_RSP;
        case 2012: return MSG_ID_DEMO8_REQ;
        case 2013: return MSG_ID_DEMO8_RSP;
        case 2014: return MSG_ID_DEMO9_REQ;
        case 2015: return MSG_ID_DEMO9_RSP;
        case 2016: return MSG_ID_DEMO10_REQ;
        case 2017: return MSG_ID_DEMO10_RSP;
        case 2018: return MSG_ID_DEMO20_REQ;
        case 2019: return MSG_ID_DEMO20_RSP;
        case 2020: return MSG_ID_DEMO50_REQ;
        case 2021: return MSG_ID_DEMO50_RSP;
        case 2022: return MSG_ID_DEMO90_REQ;
        case 2023: return MSG_ID_DEMO90_RSP;
        case 2024: return MSG_ID_DEMO2_NFY;
        case 2025: return MSG_ID_DEMO5_NFY;
        case 2026: return MSG_ID_DEMO9_NFY;
        case 2027: return MSG_ID_DEMO301_REQ;
        case 2028: return MSG_ID_DEMO301_RSP;
        case 2029: return MSG_ID_DEMO301_NFY;
        case 2030: return MSG_ID_DEMO302_REQ;
        case 2031: return MSG_ID_DEMO302_RSP;
        case 2032: return MSG_ID_DEMO303_REQ;
        case 2033: return MSG_ID_DEMO303_RSP;
        case 2034: return MSG_ID_DEMO1002_REQ;
        case 2035: return MSG_ID_DEMO1002_RSP;
        case 2036: return MSG_ID_DEMO1003_REQ;
        case 2037: return MSG_ID_DEMO1003_RSP;
        case 2038: return MSG_ID_DEMO1004_REQ;
        case 2039: return MSG_ID_DEMO1004_RSP;
        case 2040: return MSG_ID_DEMO1005_REQ;
        case 2041: return MSG_ID_DEMO1005_RSP;
        case 2042: return MSG_ID_DEMO1006_REQ;
        case 2043: return MSG_ID_DEMO1006_RSP;
        case 2044: return MSG_ID_DEMO1007_REQ;
        case 2045: return MSG_ID_DEMO1007_RSP;
        case 2046: return MSG_ID_DEMO1008_REQ;
        case 2047: return MSG_ID_DEMO1008_RSP;
        case 2048: return MSG_ID_DEMO1009_REQ;
        case 2049: return MSG_ID_DEMO1009_RSP;
        case 2050: return MSG_ID_DEMO1010_REQ;
        case 2051: return MSG_ID_DEMO1010_RSP;
        case 2052: return MSG_ID_DEMO1020_REQ;
        case 2053: return MSG_ID_DEMO1020_RSP;
        case 2054: return MSG_ID_DEMO1050_REQ;
        case 2055: return MSG_ID_DEMO1050_RSP;
        case 2056: return MSG_ID_DEMO1090_REQ;
        case 2057: return MSG_ID_DEMO1090_RSP;
        case 2058: return MSG_ID_DEMO1002_NFY;
        case 2059: return MSG_ID_DEMO1005_NFY;
        case 2060: return MSG_ID_DEMO1009_NFY;
        case 2061: return MSG_ID_DEMO2002_REQ;
        case 2062: return MSG_ID_DEMO2002_RSP;
        case 2063: return MSG_ID_DEMO2003_REQ;
        case 2064: return MSG_ID_DEMO2003_RSP;
        case 2065: return MSG_ID_DEMO2004_REQ;
        case 2066: return MSG_ID_DEMO2004_RSP;
        case 2067: return MSG_ID_DEMO2005_REQ;
        case 2068: return MSG_ID_DEMO2005_RSP;
        case 2069: return MSG_ID_DEMO2006_REQ;
        case 2070: return MSG_ID_DEMO2006_RSP;
        case 2071: return MSG_ID_DEMO2007_REQ;
        case 2072: return MSG_ID_DEMO2007_RSP;
        case 2073: return MSG_ID_DEMO2008_REQ;
        case 2074: return MSG_ID_DEMO2008_RSP;
        case 2075: return MSG_ID_DEMO2009_REQ;
        case 2076: return MSG_ID_DEMO2009_RSP;
        case 2077: return MSG_ID_DEMO2010_REQ;
        case 2078: return MSG_ID_DEMO2010_RSP;
        case 2079: return MSG_ID_DEMO2020_REQ;
        case 2080: return MSG_ID_DEMO2020_RSP;
        case 2081: return MSG_ID_DEMO2050_REQ;
        case 2082: return MSG_ID_DEMO2050_RSP;
        case 2083: return MSG_ID_DEMO2090_REQ;
        case 2084: return MSG_ID_DEMO2090_RSP;
        case 2085: return MSG_ID_DEMO2002_NFY;
        case 2086: return MSG_ID_DEMO2005_NFY;
        case 2087: return MSG_ID_DEMO2009_NFY;
        case 2088: return MSG_ID_DEMO3002_REQ;
        case 2089: return MSG_ID_DEMO3002_RSP;
        case 2090: return MSG_ID_DEMO3003_REQ;
        case 2091: return MSG_ID_DEMO3003_RSP;
        case 2092: return MSG_ID_DEMO3004_REQ;
        case 2093: return MSG_ID_DEMO3004_RSP;
        case 2094: return MSG_ID_DEMO3005_REQ;
        case 2095: return MSG_ID_DEMO3005_RSP;
        case 2096: return MSG_ID_DEMO3006_REQ;
        case 2097: return MSG_ID_DEMO3006_RSP;
        case 2098: return MSG_ID_DEMO3007_REQ;
        case 2099: return MSG_ID_DEMO3007_RSP;
        case 2100: return MSG_ID_DEMO3008_REQ;
        case 2101: return MSG_ID_DEMO3008_RSP;
        case 2102: return MSG_ID_DEMO3009_REQ;
        case 2103: return MSG_ID_DEMO3009_RSP;
        case 2104: return MSG_ID_DEMO3010_REQ;
        case 2105: return MSG_ID_DEMO3010_RSP;
        case 2106: return MSG_ID_DEMO3020_REQ;
        case 2107: return MSG_ID_DEMO3020_RSP;
        case 2108: return MSG_ID_DEMO3050_REQ;
        case 2109: return MSG_ID_DEMO3050_RSP;
        case 2110: return MSG_ID_DEMO3090_REQ;
        case 2111: return MSG_ID_DEMO3090_RSP;
        case 2112: return MSG_ID_DEMO3002_NFY;
        case 2113: return MSG_ID_DEMO3005_NFY;
        case 2114: return MSG_ID_DEMO3009_NFY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
            public MsgID findValueByNumber(int number) {
              return MsgID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsgId.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgID[] VALUES = values();

    public static MsgID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.moon.demo.ss.MsgID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ss_msg_id.proto\022\020com.moon.demo.ss*\367\026\n\005" +
      "MsgID\022\020\n\014PLACE_HOLDER\020\000\022\025\n\020MSG_ID_DEMO2_" +
      "REQ\020\320\017\022\025\n\020MSG_ID_DEMO2_RSP\020\321\017\022\025\n\020MSG_ID_" +
      "DEMO3_REQ\020\322\017\022\025\n\020MSG_ID_DEMO3_RSP\020\323\017\022\025\n\020M" +
      "SG_ID_DEMO4_REQ\020\324\017\022\025\n\020MSG_ID_DEMO4_RSP\020\325" +
      "\017\022\025\n\020MSG_ID_DEMO5_REQ\020\326\017\022\025\n\020MSG_ID_DEMO5" +
      "_RSP\020\327\017\022\025\n\020MSG_ID_DEMO6_REQ\020\330\017\022\025\n\020MSG_ID" +
      "_DEMO6_RSP\020\331\017\022\025\n\020MSG_ID_DEMO7_REQ\020\332\017\022\025\n\020" +
      "MSG_ID_DEMO7_RSP\020\333\017\022\025\n\020MSG_ID_DEMO8_REQ\020" +
      "\334\017\022\025\n\020MSG_ID_DEMO8_RSP\020\335\017\022\025\n\020MSG_ID_DEMO" +
      "9_REQ\020\336\017\022\025\n\020MSG_ID_DEMO9_RSP\020\337\017\022\026\n\021MSG_I" +
      "D_DEMO10_REQ\020\340\017\022\026\n\021MSG_ID_DEMO10_RSP\020\341\017\022" +
      "\026\n\021MSG_ID_DEMO20_REQ\020\342\017\022\026\n\021MSG_ID_DEMO20" +
      "_RSP\020\343\017\022\026\n\021MSG_ID_DEMO50_REQ\020\344\017\022\026\n\021MSG_I" +
      "D_DEMO50_RSP\020\345\017\022\026\n\021MSG_ID_DEMO90_REQ\020\346\017\022" +
      "\026\n\021MSG_ID_DEMO90_RSP\020\347\017\022\025\n\020MSG_ID_DEMO2_" +
      "NFY\020\350\017\022\025\n\020MSG_ID_DEMO5_NFY\020\351\017\022\025\n\020MSG_ID_" +
      "DEMO9_NFY\020\352\017\022\027\n\022MSG_ID_DEMO301_REQ\020\353\017\022\027\n" +
      "\022MSG_ID_DEMO301_RSP\020\354\017\022\027\n\022MSG_ID_DEMO301" +
      "_NFY\020\355\017\022\027\n\022MSG_ID_DEMO302_REQ\020\356\017\022\027\n\022MSG_" +
      "ID_DEMO302_RSP\020\357\017\022\027\n\022MSG_ID_DEMO303_REQ\020" +
      "\360\017\022\027\n\022MSG_ID_DEMO303_RSP\020\361\017\022\030\n\023MSG_ID_DE" +
      "MO1002_REQ\020\362\017\022\030\n\023MSG_ID_DEMO1002_RSP\020\363\017\022" +
      "\030\n\023MSG_ID_DEMO1003_REQ\020\364\017\022\030\n\023MSG_ID_DEMO" +
      "1003_RSP\020\365\017\022\030\n\023MSG_ID_DEMO1004_REQ\020\366\017\022\030\n" +
      "\023MSG_ID_DEMO1004_RSP\020\367\017\022\030\n\023MSG_ID_DEMO10" +
      "05_REQ\020\370\017\022\030\n\023MSG_ID_DEMO1005_RSP\020\371\017\022\030\n\023M" +
      "SG_ID_DEMO1006_REQ\020\372\017\022\030\n\023MSG_ID_DEMO1006" +
      "_RSP\020\373\017\022\030\n\023MSG_ID_DEMO1007_REQ\020\374\017\022\030\n\023MSG" +
      "_ID_DEMO1007_RSP\020\375\017\022\030\n\023MSG_ID_DEMO1008_R" +
      "EQ\020\376\017\022\030\n\023MSG_ID_DEMO1008_RSP\020\377\017\022\030\n\023MSG_I" +
      "D_DEMO1009_REQ\020\200\020\022\030\n\023MSG_ID_DEMO1009_RSP" +
      "\020\201\020\022\030\n\023MSG_ID_DEMO1010_REQ\020\202\020\022\030\n\023MSG_ID_" +
      "DEMO1010_RSP\020\203\020\022\030\n\023MSG_ID_DEMO1020_REQ\020\204" +
      "\020\022\030\n\023MSG_ID_DEMO1020_RSP\020\205\020\022\030\n\023MSG_ID_DE" +
      "MO1050_REQ\020\206\020\022\030\n\023MSG_ID_DEMO1050_RSP\020\207\020\022" +
      "\030\n\023MSG_ID_DEMO1090_REQ\020\210\020\022\030\n\023MSG_ID_DEMO" +
      "1090_RSP\020\211\020\022\030\n\023MSG_ID_DEMO1002_NFY\020\212\020\022\030\n" +
      "\023MSG_ID_DEMO1005_NFY\020\213\020\022\030\n\023MSG_ID_DEMO10" +
      "09_NFY\020\214\020\022\030\n\023MSG_ID_DEMO2002_REQ\020\215\020\022\030\n\023M" +
      "SG_ID_DEMO2002_RSP\020\216\020\022\030\n\023MSG_ID_DEMO2003" +
      "_REQ\020\217\020\022\030\n\023MSG_ID_DEMO2003_RSP\020\220\020\022\030\n\023MSG" +
      "_ID_DEMO2004_REQ\020\221\020\022\030\n\023MSG_ID_DEMO2004_R" +
      "SP\020\222\020\022\030\n\023MSG_ID_DEMO2005_REQ\020\223\020\022\030\n\023MSG_I" +
      "D_DEMO2005_RSP\020\224\020\022\030\n\023MSG_ID_DEMO2006_REQ" +
      "\020\225\020\022\030\n\023MSG_ID_DEMO2006_RSP\020\226\020\022\030\n\023MSG_ID_" +
      "DEMO2007_REQ\020\227\020\022\030\n\023MSG_ID_DEMO2007_RSP\020\230" +
      "\020\022\030\n\023MSG_ID_DEMO2008_REQ\020\231\020\022\030\n\023MSG_ID_DE" +
      "MO2008_RSP\020\232\020\022\030\n\023MSG_ID_DEMO2009_REQ\020\233\020\022" +
      "\030\n\023MSG_ID_DEMO2009_RSP\020\234\020\022\030\n\023MSG_ID_DEMO" +
      "2010_REQ\020\235\020\022\030\n\023MSG_ID_DEMO2010_RSP\020\236\020\022\030\n" +
      "\023MSG_ID_DEMO2020_REQ\020\237\020\022\030\n\023MSG_ID_DEMO20" +
      "20_RSP\020\240\020\022\030\n\023MSG_ID_DEMO2050_REQ\020\241\020\022\030\n\023M" +
      "SG_ID_DEMO2050_RSP\020\242\020\022\030\n\023MSG_ID_DEMO2090" +
      "_REQ\020\243\020\022\030\n\023MSG_ID_DEMO2090_RSP\020\244\020\022\030\n\023MSG" +
      "_ID_DEMO2002_NFY\020\245\020\022\030\n\023MSG_ID_DEMO2005_N" +
      "FY\020\246\020\022\030\n\023MSG_ID_DEMO2009_NFY\020\247\020\022\030\n\023MSG_I" +
      "D_DEMO3002_REQ\020\250\020\022\030\n\023MSG_ID_DEMO3002_RSP" +
      "\020\251\020\022\030\n\023MSG_ID_DEMO3003_REQ\020\252\020\022\030\n\023MSG_ID_" +
      "DEMO3003_RSP\020\253\020\022\030\n\023MSG_ID_DEMO3004_REQ\020\254" +
      "\020\022\030\n\023MSG_ID_DEMO3004_RSP\020\255\020\022\030\n\023MSG_ID_DE" +
      "MO3005_REQ\020\256\020\022\030\n\023MSG_ID_DEMO3005_RSP\020\257\020\022" +
      "\030\n\023MSG_ID_DEMO3006_REQ\020\260\020\022\030\n\023MSG_ID_DEMO" +
      "3006_RSP\020\261\020\022\030\n\023MSG_ID_DEMO3007_REQ\020\262\020\022\030\n" +
      "\023MSG_ID_DEMO3007_RSP\020\263\020\022\030\n\023MSG_ID_DEMO30" +
      "08_REQ\020\264\020\022\030\n\023MSG_ID_DEMO3008_RSP\020\265\020\022\030\n\023M" +
      "SG_ID_DEMO3009_REQ\020\266\020\022\030\n\023MSG_ID_DEMO3009" +
      "_RSP\020\267\020\022\030\n\023MSG_ID_DEMO3010_REQ\020\270\020\022\030\n\023MSG" +
      "_ID_DEMO3010_RSP\020\271\020\022\030\n\023MSG_ID_DEMO3020_R" +
      "EQ\020\272\020\022\030\n\023MSG_ID_DEMO3020_RSP\020\273\020\022\030\n\023MSG_I" +
      "D_DEMO3050_REQ\020\274\020\022\030\n\023MSG_ID_DEMO3050_RSP" +
      "\020\275\020\022\030\n\023MSG_ID_DEMO3090_REQ\020\276\020\022\030\n\023MSG_ID_" +
      "DEMO3090_RSP\020\277\020\022\030\n\023MSG_ID_DEMO3002_NFY\020\300" +
      "\020\022\030\n\023MSG_ID_DEMO3005_NFY\020\301\020\022\030\n\023MSG_ID_DE" +
      "MO3009_NFY\020\302\020b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
