// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ss_msg_id.proto

package com.moon.demo.ss;

public final class SsMsgId {
  private SsMsgId() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.moon.demo.ss.MsgID}
   */
  public enum MsgID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLACE_HOLDER = 0;</code>
     */
    PLACE_HOLDER(0),
    /**
     * <code>MSG_ID_DEMO2_REQ = 2000;</code>
     */
    MSG_ID_DEMO2_REQ(2000),
    /**
     * <code>MSG_ID_DEMO2_RSP = 2001;</code>
     */
    MSG_ID_DEMO2_RSP(2001),
    /**
     * <code>MSG_ID_DEMO3_REQ = 2002;</code>
     */
    MSG_ID_DEMO3_REQ(2002),
    /**
     * <code>MSG_ID_DEMO3_RSP = 2003;</code>
     */
    MSG_ID_DEMO3_RSP(2003),
    /**
     * <code>MSG_ID_DEMO4_REQ = 2004;</code>
     */
    MSG_ID_DEMO4_REQ(2004),
    /**
     * <code>MSG_ID_DEMO4_RSP = 2005;</code>
     */
    MSG_ID_DEMO4_RSP(2005),
    /**
     * <code>MSG_ID_DEMO5_REQ = 2006;</code>
     */
    MSG_ID_DEMO5_REQ(2006),
    /**
     * <code>MSG_ID_DEMO5_RSP = 2007;</code>
     */
    MSG_ID_DEMO5_RSP(2007),
    /**
     * <code>MSG_ID_DEMO6_REQ = 2008;</code>
     */
    MSG_ID_DEMO6_REQ(2008),
    /**
     * <code>MSG_ID_DEMO6_RSP = 2009;</code>
     */
    MSG_ID_DEMO6_RSP(2009),
    /**
     * <code>MSG_ID_DEMO7_REQ = 2010;</code>
     */
    MSG_ID_DEMO7_REQ(2010),
    /**
     * <code>MSG_ID_DEMO7_RSP = 2011;</code>
     */
    MSG_ID_DEMO7_RSP(2011),
    /**
     * <code>MSG_ID_DEMO8_REQ = 2012;</code>
     */
    MSG_ID_DEMO8_REQ(2012),
    /**
     * <code>MSG_ID_DEMO8_RSP = 2013;</code>
     */
    MSG_ID_DEMO8_RSP(2013),
    /**
     * <code>MSG_ID_DEMO9_REQ = 2014;</code>
     */
    MSG_ID_DEMO9_REQ(2014),
    /**
     * <code>MSG_ID_DEMO9_RSP = 2015;</code>
     */
    MSG_ID_DEMO9_RSP(2015),
    /**
     * <code>MSG_ID_DEMO10_REQ = 2016;</code>
     */
    MSG_ID_DEMO10_REQ(2016),
    /**
     * <code>MSG_ID_DEMO10_RSP = 2017;</code>
     */
    MSG_ID_DEMO10_RSP(2017),
    /**
     * <code>MSG_ID_DEMO20_REQ = 2018;</code>
     */
    MSG_ID_DEMO20_REQ(2018),
    /**
     * <code>MSG_ID_DEMO20_RSP = 2019;</code>
     */
    MSG_ID_DEMO20_RSP(2019),
    /**
     * <code>MSG_ID_DEMO50_REQ = 2020;</code>
     */
    MSG_ID_DEMO50_REQ(2020),
    /**
     * <code>MSG_ID_DEMO50_RSP = 2021;</code>
     */
    MSG_ID_DEMO50_RSP(2021),
    /**
     * <code>MSG_ID_DEMO90_REQ = 2022;</code>
     */
    MSG_ID_DEMO90_REQ(2022),
    /**
     * <code>MSG_ID_DEMO90_RSP = 2023;</code>
     */
    MSG_ID_DEMO90_RSP(2023),
    /**
     * <code>MSG_ID_DEMO2_NFY = 2024;</code>
     */
    MSG_ID_DEMO2_NFY(2024),
    /**
     * <code>MSG_ID_DEMO5_NFY = 2025;</code>
     */
    MSG_ID_DEMO5_NFY(2025),
    /**
     * <code>MSG_ID_DEMO9_NFY = 2026;</code>
     */
    MSG_ID_DEMO9_NFY(2026),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLACE_HOLDER = 0;</code>
     */
    public static final int PLACE_HOLDER_VALUE = 0;
    /**
     * <code>MSG_ID_DEMO2_REQ = 2000;</code>
     */
    public static final int MSG_ID_DEMO2_REQ_VALUE = 2000;
    /**
     * <code>MSG_ID_DEMO2_RSP = 2001;</code>
     */
    public static final int MSG_ID_DEMO2_RSP_VALUE = 2001;
    /**
     * <code>MSG_ID_DEMO3_REQ = 2002;</code>
     */
    public static final int MSG_ID_DEMO3_REQ_VALUE = 2002;
    /**
     * <code>MSG_ID_DEMO3_RSP = 2003;</code>
     */
    public static final int MSG_ID_DEMO3_RSP_VALUE = 2003;
    /**
     * <code>MSG_ID_DEMO4_REQ = 2004;</code>
     */
    public static final int MSG_ID_DEMO4_REQ_VALUE = 2004;
    /**
     * <code>MSG_ID_DEMO4_RSP = 2005;</code>
     */
    public static final int MSG_ID_DEMO4_RSP_VALUE = 2005;
    /**
     * <code>MSG_ID_DEMO5_REQ = 2006;</code>
     */
    public static final int MSG_ID_DEMO5_REQ_VALUE = 2006;
    /**
     * <code>MSG_ID_DEMO5_RSP = 2007;</code>
     */
    public static final int MSG_ID_DEMO5_RSP_VALUE = 2007;
    /**
     * <code>MSG_ID_DEMO6_REQ = 2008;</code>
     */
    public static final int MSG_ID_DEMO6_REQ_VALUE = 2008;
    /**
     * <code>MSG_ID_DEMO6_RSP = 2009;</code>
     */
    public static final int MSG_ID_DEMO6_RSP_VALUE = 2009;
    /**
     * <code>MSG_ID_DEMO7_REQ = 2010;</code>
     */
    public static final int MSG_ID_DEMO7_REQ_VALUE = 2010;
    /**
     * <code>MSG_ID_DEMO7_RSP = 2011;</code>
     */
    public static final int MSG_ID_DEMO7_RSP_VALUE = 2011;
    /**
     * <code>MSG_ID_DEMO8_REQ = 2012;</code>
     */
    public static final int MSG_ID_DEMO8_REQ_VALUE = 2012;
    /**
     * <code>MSG_ID_DEMO8_RSP = 2013;</code>
     */
    public static final int MSG_ID_DEMO8_RSP_VALUE = 2013;
    /**
     * <code>MSG_ID_DEMO9_REQ = 2014;</code>
     */
    public static final int MSG_ID_DEMO9_REQ_VALUE = 2014;
    /**
     * <code>MSG_ID_DEMO9_RSP = 2015;</code>
     */
    public static final int MSG_ID_DEMO9_RSP_VALUE = 2015;
    /**
     * <code>MSG_ID_DEMO10_REQ = 2016;</code>
     */
    public static final int MSG_ID_DEMO10_REQ_VALUE = 2016;
    /**
     * <code>MSG_ID_DEMO10_RSP = 2017;</code>
     */
    public static final int MSG_ID_DEMO10_RSP_VALUE = 2017;
    /**
     * <code>MSG_ID_DEMO20_REQ = 2018;</code>
     */
    public static final int MSG_ID_DEMO20_REQ_VALUE = 2018;
    /**
     * <code>MSG_ID_DEMO20_RSP = 2019;</code>
     */
    public static final int MSG_ID_DEMO20_RSP_VALUE = 2019;
    /**
     * <code>MSG_ID_DEMO50_REQ = 2020;</code>
     */
    public static final int MSG_ID_DEMO50_REQ_VALUE = 2020;
    /**
     * <code>MSG_ID_DEMO50_RSP = 2021;</code>
     */
    public static final int MSG_ID_DEMO50_RSP_VALUE = 2021;
    /**
     * <code>MSG_ID_DEMO90_REQ = 2022;</code>
     */
    public static final int MSG_ID_DEMO90_REQ_VALUE = 2022;
    /**
     * <code>MSG_ID_DEMO90_RSP = 2023;</code>
     */
    public static final int MSG_ID_DEMO90_RSP_VALUE = 2023;
    /**
     * <code>MSG_ID_DEMO2_NFY = 2024;</code>
     */
    public static final int MSG_ID_DEMO2_NFY_VALUE = 2024;
    /**
     * <code>MSG_ID_DEMO5_NFY = 2025;</code>
     */
    public static final int MSG_ID_DEMO5_NFY_VALUE = 2025;
    /**
     * <code>MSG_ID_DEMO9_NFY = 2026;</code>
     */
    public static final int MSG_ID_DEMO9_NFY_VALUE = 2026;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MsgID valueOf(int value) {
      return forNumber(value);
    }

    public static MsgID forNumber(int value) {
      switch (value) {
        case 0: return PLACE_HOLDER;
        case 2000: return MSG_ID_DEMO2_REQ;
        case 2001: return MSG_ID_DEMO2_RSP;
        case 2002: return MSG_ID_DEMO3_REQ;
        case 2003: return MSG_ID_DEMO3_RSP;
        case 2004: return MSG_ID_DEMO4_REQ;
        case 2005: return MSG_ID_DEMO4_RSP;
        case 2006: return MSG_ID_DEMO5_REQ;
        case 2007: return MSG_ID_DEMO5_RSP;
        case 2008: return MSG_ID_DEMO6_REQ;
        case 2009: return MSG_ID_DEMO6_RSP;
        case 2010: return MSG_ID_DEMO7_REQ;
        case 2011: return MSG_ID_DEMO7_RSP;
        case 2012: return MSG_ID_DEMO8_REQ;
        case 2013: return MSG_ID_DEMO8_RSP;
        case 2014: return MSG_ID_DEMO9_REQ;
        case 2015: return MSG_ID_DEMO9_RSP;
        case 2016: return MSG_ID_DEMO10_REQ;
        case 2017: return MSG_ID_DEMO10_RSP;
        case 2018: return MSG_ID_DEMO20_REQ;
        case 2019: return MSG_ID_DEMO20_RSP;
        case 2020: return MSG_ID_DEMO50_REQ;
        case 2021: return MSG_ID_DEMO50_RSP;
        case 2022: return MSG_ID_DEMO90_REQ;
        case 2023: return MSG_ID_DEMO90_RSP;
        case 2024: return MSG_ID_DEMO2_NFY;
        case 2025: return MSG_ID_DEMO5_NFY;
        case 2026: return MSG_ID_DEMO9_NFY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MsgID> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
            public MsgID findValueByNumber(int number) {
              return MsgID.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.moon.demo.ss.SsMsgId.getDescriptor().getEnumTypes().get(0);
    }

    private static final MsgID[] VALUES = values();

    public static MsgID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MsgID(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.moon.demo.ss.MsgID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017ss_msg_id.proto\022\020com.moon.demo.ss*\216\005\n\005" +
      "MsgID\022\020\n\014PLACE_HOLDER\020\000\022\025\n\020MSG_ID_DEMO2_" +
      "REQ\020\320\017\022\025\n\020MSG_ID_DEMO2_RSP\020\321\017\022\025\n\020MSG_ID_" +
      "DEMO3_REQ\020\322\017\022\025\n\020MSG_ID_DEMO3_RSP\020\323\017\022\025\n\020M" +
      "SG_ID_DEMO4_REQ\020\324\017\022\025\n\020MSG_ID_DEMO4_RSP\020\325" +
      "\017\022\025\n\020MSG_ID_DEMO5_REQ\020\326\017\022\025\n\020MSG_ID_DEMO5" +
      "_RSP\020\327\017\022\025\n\020MSG_ID_DEMO6_REQ\020\330\017\022\025\n\020MSG_ID" +
      "_DEMO6_RSP\020\331\017\022\025\n\020MSG_ID_DEMO7_REQ\020\332\017\022\025\n\020" +
      "MSG_ID_DEMO7_RSP\020\333\017\022\025\n\020MSG_ID_DEMO8_REQ\020" +
      "\334\017\022\025\n\020MSG_ID_DEMO8_RSP\020\335\017\022\025\n\020MSG_ID_DEMO" +
      "9_REQ\020\336\017\022\025\n\020MSG_ID_DEMO9_RSP\020\337\017\022\026\n\021MSG_I" +
      "D_DEMO10_REQ\020\340\017\022\026\n\021MSG_ID_DEMO10_RSP\020\341\017\022" +
      "\026\n\021MSG_ID_DEMO20_REQ\020\342\017\022\026\n\021MSG_ID_DEMO20" +
      "_RSP\020\343\017\022\026\n\021MSG_ID_DEMO50_REQ\020\344\017\022\026\n\021MSG_I" +
      "D_DEMO50_RSP\020\345\017\022\026\n\021MSG_ID_DEMO90_REQ\020\346\017\022" +
      "\026\n\021MSG_ID_DEMO90_RSP\020\347\017\022\025\n\020MSG_ID_DEMO2_" +
      "NFY\020\350\017\022\025\n\020MSG_ID_DEMO5_NFY\020\351\017\022\025\n\020MSG_ID_" +
      "DEMO9_NFY\020\352\017b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
