# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ss_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ss_msg.proto',
  package='com.moon.demo.proto.ss',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0css_msg.proto\x12\x16\x63om.moon.demo.proto.ss\x1a\x0c\x63ommon.proto\"!\n\tGlobalReq\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"9\n\tGlobalRsp\x12,\n\x07\x65rr_ctx\x18\x01 \x01(\x0b\x32\x1b.com.moon.demo.proto.ErrCtx\"\"\n\x08\x44\x65mo1Req\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\x0b\n\x03udp\x18\x02 \x01(\x08\"8\n\x08\x44\x65mo1Rsp\x12,\n\x07\x65rr_ctx\x18\x01 \x01(\x0b\x32\x1b.com.moon.demo.proto.ErrCtx\"\x15\n\x08\x44\x65mo1Nfy\x12\t\n\x01\x61\x18\x01 \x01(\x05\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_GLOBALREQ = _descriptor.Descriptor(
  name='GlobalReq',
  full_name='com.moon.demo.proto.ss.GlobalReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='com.moon.demo.proto.ss.GlobalReq.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='com.moon.demo.proto.ss.GlobalReq.b', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=87,
)


_GLOBALRSP = _descriptor.Descriptor(
  name='GlobalRsp',
  full_name='com.moon.demo.proto.ss.GlobalRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_ctx', full_name='com.moon.demo.proto.ss.GlobalRsp.err_ctx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=146,
)


_DEMO1REQ = _descriptor.Descriptor(
  name='Demo1Req',
  full_name='com.moon.demo.proto.ss.Demo1Req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='com.moon.demo.proto.ss.Demo1Req.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='udp', full_name='com.moon.demo.proto.ss.Demo1Req.udp', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=182,
)


_DEMO1RSP = _descriptor.Descriptor(
  name='Demo1Rsp',
  full_name='com.moon.demo.proto.ss.Demo1Rsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_ctx', full_name='com.moon.demo.proto.ss.Demo1Rsp.err_ctx', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=240,
)


_DEMO1NFY = _descriptor.Descriptor(
  name='Demo1Nfy',
  full_name='com.moon.demo.proto.ss.Demo1Nfy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='com.moon.demo.proto.ss.Demo1Nfy.a', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=263,
)

_GLOBALRSP.fields_by_name['err_ctx'].message_type = common__pb2._ERRCTX
_DEMO1RSP.fields_by_name['err_ctx'].message_type = common__pb2._ERRCTX
DESCRIPTOR.message_types_by_name['GlobalReq'] = _GLOBALREQ
DESCRIPTOR.message_types_by_name['GlobalRsp'] = _GLOBALRSP
DESCRIPTOR.message_types_by_name['Demo1Req'] = _DEMO1REQ
DESCRIPTOR.message_types_by_name['Demo1Rsp'] = _DEMO1RSP
DESCRIPTOR.message_types_by_name['Demo1Nfy'] = _DEMO1NFY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalReq = _reflection.GeneratedProtocolMessageType('GlobalReq', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALREQ,
  __module__ = 'ss_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.GlobalReq)
  ))
_sym_db.RegisterMessage(GlobalReq)

GlobalRsp = _reflection.GeneratedProtocolMessageType('GlobalRsp', (_message.Message,), dict(
  DESCRIPTOR = _GLOBALRSP,
  __module__ = 'ss_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.GlobalRsp)
  ))
_sym_db.RegisterMessage(GlobalRsp)

Demo1Req = _reflection.GeneratedProtocolMessageType('Demo1Req', (_message.Message,), dict(
  DESCRIPTOR = _DEMO1REQ,
  __module__ = 'ss_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Req)
  ))
_sym_db.RegisterMessage(Demo1Req)

Demo1Rsp = _reflection.GeneratedProtocolMessageType('Demo1Rsp', (_message.Message,), dict(
  DESCRIPTOR = _DEMO1RSP,
  __module__ = 'ss_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Rsp)
  ))
_sym_db.RegisterMessage(Demo1Rsp)

Demo1Nfy = _reflection.GeneratedProtocolMessageType('Demo1Nfy', (_message.Message,), dict(
  DESCRIPTOR = _DEMO1NFY,
  __module__ = 'ss_msg_pb2'
  # @@protoc_insertion_point(class_scope:com.moon.demo.proto.ss.Demo1Nfy)
  ))
_sym_db.RegisterMessage(Demo1Nfy)


# @@protoc_insertion_point(module_scope)
